# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_global_apps_custom_app_id_details_app_lists_get_response import V1GlobalAppsCustomAppIdDetailsAppListsGetResponse

class TestV1GlobalAppsCustomAppIdDetailsAppListsGetResponse(unittest.TestCase):
    """V1GlobalAppsCustomAppIdDetailsAppListsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GlobalAppsCustomAppIdDetailsAppListsGetResponse:
        """Test V1GlobalAppsCustomAppIdDetailsAppListsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GlobalAppsCustomAppIdDetailsAppListsGetResponse`
        """
        model = V1GlobalAppsCustomAppIdDetailsAppListsGetResponse()
        if include_optional:
            return V1GlobalAppsCustomAppIdDetailsAppListsGetResponse(
                app_lists = [
                    graphiant_sdk.models.mana_v2_app.manaV2App(
                        description = 'example string', 
                        identifier = graphiant_sdk.models.mana_v2_app_identifier.manaV2AppIdentifier(
                            id = 1234567891011, 
                            type = 'ENUM_VALUE', ), 
                        name = 'example string', )
                    ]
            )
        else:
            return V1GlobalAppsCustomAppIdDetailsAppListsGetResponse(
        )
        """

    def testV1GlobalAppsCustomAppIdDetailsAppListsGetResponse(self):
        """Test V1GlobalAppsCustomAppIdDetailsAppListsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
