# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_monitoring_circuits_bandwidth_post_response_data import V1MonitoringCircuitsBandwidthPostResponseData

class TestV1MonitoringCircuitsBandwidthPostResponseData(unittest.TestCase):
    """V1MonitoringCircuitsBandwidthPostResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1MonitoringCircuitsBandwidthPostResponseData:
        """Test V1MonitoringCircuitsBandwidthPostResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1MonitoringCircuitsBandwidthPostResponseData`
        """
        model = V1MonitoringCircuitsBandwidthPostResponseData()
        if include_optional:
            return V1MonitoringCircuitsBandwidthPostResponseData(
                selector = graphiant_sdk.models.common_circuit_bandwidth_stats_selector.commonCircuitBandwidthStatsSelector(
                    circuit_name = 'example string', ),
                stats = [
                    graphiant_sdk.models.common_circuit_bandwidth_stats.commonCircuitBandwidthStats(
                        dl_bw_kbps = 123.45, 
                        ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), 
                        ul_bw_kbps = 123.45, )
                    ]
            )
        else:
            return V1MonitoringCircuitsBandwidthPostResponseData(
        )
        """

    def testV1MonitoringCircuitsBandwidthPostResponseData(self):
        """Test V1MonitoringCircuitsBandwidthPostResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
