# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.statsmon_backbonehealth_get_qoe_matrix_response import StatsmonBackbonehealthGetQoeMatrixResponse

class TestStatsmonBackbonehealthGetQoeMatrixResponse(unittest.TestCase):
    """StatsmonBackbonehealthGetQoeMatrixResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsmonBackbonehealthGetQoeMatrixResponse:
        """Test StatsmonBackbonehealthGetQoeMatrixResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsmonBackbonehealthGetQoeMatrixResponse`
        """
        model = StatsmonBackbonehealthGetQoeMatrixResponse()
        if include_optional:
            return StatsmonBackbonehealthGetQoeMatrixResponse(
                devices = [
                    graphiant_sdk.models.statsmon_backbonehealth_get_qoe_matrix_response_devices_summary.statsmonBackbonehealthGetQOEMatrixResponseDevicesSummary(
                        device_id = 1234567891011, 
                        device_name = 'example string', 
                        region = graphiant_sdk.models.statsmon_troubleshooting_region.statsmonTroubleshootingRegion(
                            region_id = 123, 
                            region_name = 'example string', ), )
                    ],
                qoe_matrix = [
                    graphiant_sdk.models.statsmon_backbonehealth_get_qoe_matrix_response_qoe_session_summary.statsmonBackbonehealthGetQOEMatrixResponseQoeSessionSummary(
                        box = [
                            graphiant_sdk.models.statsmon_backbonehealth_get_qoe_matrix_response_qoe_session_summary_qoe_session_box.statsmonBackbonehealthGetQOEMatrixResponseQoeSessionSummaryQoeSessionBox(
                                delay_value = 123.45, 
                                end_time = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                                    nanos = 123, 
                                    seconds = 1234567891011, ), 
                                jitter_value = 123.45, 
                                loss_value = 123.45, 
                                start_time = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                                    nanos = 123, 
                                    seconds = 1234567891011, ), 
                                status = 'ENUM_VALUE', 
                                value = 123.45, )
                            ], 
                        device_id = 1234567891011, 
                        device_region = graphiant_sdk.models.statsmon_troubleshooting_region.statsmonTroubleshootingRegion(
                            region_id = 123, 
                            region_name = 'example string', ), 
                        peer_device_id = 1234567891011, 
                        peer_device_region = graphiant_sdk.models.statsmon_troubleshooting_region.statsmonTroubleshootingRegion(
                            region_id = 123, 
                            region_name = 'example string', ), 
                        session_name = 'example string', )
                    ]
            )
        else:
            return StatsmonBackbonehealthGetQoeMatrixResponse(
        )
        """

    def testStatsmonBackbonehealthGetQoeMatrixResponse(self):
        """Test StatsmonBackbonehealthGetQoeMatrixResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
