# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_enterprise_snapshot_get_response import V1EnterpriseSnapshotGetResponse

class TestV1EnterpriseSnapshotGetResponse(unittest.TestCase):
    """V1EnterpriseSnapshotGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1EnterpriseSnapshotGetResponse:
        """Test V1EnterpriseSnapshotGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1EnterpriseSnapshotGetResponse`
        """
        model = V1EnterpriseSnapshotGetResponse()
        if include_optional:
            return V1EnterpriseSnapshotGetResponse(
                device_snapshot_records = [
                    graphiant_sdk.models.mana_v2device_snapshot_row.manaV2deviceSnapshotRow(
                        device_id = 1234567891011, 
                        hostname = 'example string', 
                        region = 'example string', 
                        site = 'example string', 
                        snapshot_count = 123, 
                        snapshots = [
                            graphiant_sdk.models.mana_v2_device_snapshot.manaV2DeviceSnapshot(
                                author = graphiant_sdk.models.common_user_info.commonUserInfo(
                                    enterprise_id = 1234567891011, 
                                    exp = 1234567891011, 
                                    original_enterprise_id = 1234567891011, 
                                    permissions = graphiant_sdk.models.common_permissions.commonPermissions(
                                        asset_manager = 'ENUM_VALUE', 
                                        b2b = 'ENUM_VALUE', 
                                        b2b_security_profile_external = 'ENUM_VALUE', 
                                        billing_and_invoicing = 'ENUM_VALUE', 
                                        compliance = 'ENUM_VALUE', 
                                        developer_tools = 'ENUM_VALUE', 
                                        gateway = 'ENUM_VALUE', 
                                        global_services = 'ENUM_VALUE', 
                                        insights = 'ENUM_VALUE', 
                                        licensing = 'ENUM_VALUE', 
                                        logs = 'ENUM_VALUE', 
                                        monitoring_and_troubleshooting = 'ENUM_VALUE', 
                                        network_configuration = 'ENUM_VALUE', 
                                        order_status = 'ENUM_VALUE', 
                                        reports = 'ENUM_VALUE', 
                                        safety_and_security = 'ENUM_VALUE', 
                                        service_policies = 'ENUM_VALUE', 
                                        support = 'ENUM_VALUE', 
                                        user_and_tenant_management = 'ENUM_VALUE', ), 
                                    time_zone = 'example string', 
                                    user_id = 'example string', ), 
                                category = 'ENUM_VALUE', 
                                created_on = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                                    nanos = 123, 
                                    seconds = 1234567891011, ), 
                                data = graphiant_sdk.models.mana_v2_device_snapshot_data.manaV2DeviceSnapshotData(
                                    ospf_installed_route_count = 123, 
                                    t2_session_count = 123, 
                                    twamp_session_count = 123, 
                                    bfd_session_count = 123, 
                                    bgp_neighbor_ip_list = [
                                        'example string'
                                        ], 
                                    bgp_session_count = 123, 
                                    device_role = 'ENUM_VALUE', 
                                    failed_services_count = 123, 
                                    graphnos_version = 'example string', 
                                    installed_labels = 123, 
                                    ipsec_session_count = 123, 
                                    ongoing_alerts = 123, 
                                    ospf_neighbor_ip_list = [
                                        'example string'
                                        ], 
                                    ospf_session_count = 123, ), 
                                golden = True, 
                                id = 1234567891011, 
                                name = '6-1-24-status-check', )
                            ], 
                        uptime = graphiant_sdk.models.google_protobuf_duration.googleProtobufDuration(
                            nanos = 123, 
                            seconds = 1234567891011, ), )
                    ],
                device_snapshot_map = {
                    'key' : graphiant_sdk.models.mana_v2_device_snapshot_list.manaV2DeviceSnapshotList(
                        count = 123, 
                        snapshots = [
                            graphiant_sdk.models.mana_v2_device_snapshot.manaV2DeviceSnapshot(
                                author = graphiant_sdk.models.common_user_info.commonUserInfo(
                                    enterprise_id = 1234567891011, 
                                    exp = 1234567891011, 
                                    original_enterprise_id = 1234567891011, 
                                    permissions = graphiant_sdk.models.common_permissions.commonPermissions(
                                        asset_manager = 'ENUM_VALUE', 
                                        b2b = 'ENUM_VALUE', 
                                        b2b_security_profile_external = 'ENUM_VALUE', 
                                        billing_and_invoicing = 'ENUM_VALUE', 
                                        compliance = 'ENUM_VALUE', 
                                        developer_tools = 'ENUM_VALUE', 
                                        gateway = 'ENUM_VALUE', 
                                        global_services = 'ENUM_VALUE', 
                                        insights = 'ENUM_VALUE', 
                                        licensing = 'ENUM_VALUE', 
                                        logs = 'ENUM_VALUE', 
                                        monitoring_and_troubleshooting = 'ENUM_VALUE', 
                                        network_configuration = 'ENUM_VALUE', 
                                        order_status = 'ENUM_VALUE', 
                                        reports = 'ENUM_VALUE', 
                                        safety_and_security = 'ENUM_VALUE', 
                                        service_policies = 'ENUM_VALUE', 
                                        support = 'ENUM_VALUE', 
                                        user_and_tenant_management = 'ENUM_VALUE', ), 
                                    time_zone = 'example string', 
                                    user_id = 'example string', ), 
                                category = 'ENUM_VALUE', 
                                created_on = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                                    nanos = 123, 
                                    seconds = 1234567891011, ), 
                                data = graphiant_sdk.models.mana_v2_device_snapshot_data.manaV2DeviceSnapshotData(
                                    ospf_installed_route_count = 123, 
                                    t2_session_count = 123, 
                                    twamp_session_count = 123, 
                                    bfd_session_count = 123, 
                                    bgp_neighbor_ip_list = [
                                        'example string'
                                        ], 
                                    bgp_session_count = 123, 
                                    device_role = 'ENUM_VALUE', 
                                    failed_services_count = 123, 
                                    graphnos_version = 'example string', 
                                    installed_labels = 123, 
                                    ipsec_session_count = 123, 
                                    ongoing_alerts = 123, 
                                    ospf_neighbor_ip_list = [
                                        'example string'
                                        ], 
                                    ospf_session_count = 123, ), 
                                golden = True, 
                                id = 1234567891011, 
                                name = '6-1-24-status-check', )
                            ], )
                    }
            )
        else:
            return V1EnterpriseSnapshotGetResponse(
        )
        """

    def testV1EnterpriseSnapshotGetResponse(self):
        """Test V1EnterpriseSnapshotGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
