# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_devices_device_id_policy_customapplications_get_response import V1DevicesDeviceIdPolicyCustomapplicationsGetResponse

class TestV1DevicesDeviceIdPolicyCustomapplicationsGetResponse(unittest.TestCase):
    """V1DevicesDeviceIdPolicyCustomapplicationsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DevicesDeviceIdPolicyCustomapplicationsGetResponse:
        """Test V1DevicesDeviceIdPolicyCustomapplicationsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DevicesDeviceIdPolicyCustomapplicationsGetResponse`
        """
        model = V1DevicesDeviceIdPolicyCustomapplicationsGetResponse()
        if include_optional:
            return V1DevicesDeviceIdPolicyCustomapplicationsGetResponse(
                applications = [
                    graphiant_sdk.models.v1_devices_device_id_policy_customapplications_get_response_application.v1DevicesDeviceIdPolicyCustomapplicationsGetResponseApplication(
                        app_id = 1234567891011, 
                        description = 'example string', 
                        kind = 'ENUM_VALUE', 
                        name = 'example string', )
                    ],
                page_info = graphiant_sdk.models.common_page_info.commonPageInfo(
                    current_page = 1, 
                    end_cursor = 'xxxxxxy', 
                    has_next_page = False, 
                    has_prev_page = True, 
                    start_cursor = 'xxxxxx', 
                    total_pages = 4, 
                    total_records = 400, )
            )
        else:
            return V1DevicesDeviceIdPolicyCustomapplicationsGetResponse(
        )
        """

    def testV1DevicesDeviceIdPolicyCustomapplicationsGetResponse(self):
        """Test V1DevicesDeviceIdPolicyCustomapplicationsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
