# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_bwtracker_region_gateway_details_post_request import V1BwtrackerRegionGatewayDetailsPostRequest

class TestV1BwtrackerRegionGatewayDetailsPostRequest(unittest.TestCase):
    """V1BwtrackerRegionGatewayDetailsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1BwtrackerRegionGatewayDetailsPostRequest:
        """Test V1BwtrackerRegionGatewayDetailsPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1BwtrackerRegionGatewayDetailsPostRequest`
        """
        model = V1BwtrackerRegionGatewayDetailsPostRequest()
        if include_optional:
            return V1BwtrackerRegionGatewayDetailsPostRequest(
                region_id = 12345678910,
                time_window = graphiant_sdk.models.statsmon_bandwidthtracker_time_window.statsmonBandwidthtrackerTimeWindow(
                    bucket_size_sec = 123, 
                    old_ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                        nanos = 123, 
                        seconds = 1234567891011, ), 
                    recent_ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                        nanos = 123, 
                        seconds = 1234567891011, ), )
            )
        else:
            return V1BwtrackerRegionGatewayDetailsPostRequest(
        )
        """

    def testV1BwtrackerRegionGatewayDetailsPostRequest(self):
        """Test V1BwtrackerRegionGatewayDetailsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
