# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_monitoring_extranet_status_details_get_request import V2MonitoringExtranetStatusDetailsGetRequest

class TestV2MonitoringExtranetStatusDetailsGetRequest(unittest.TestCase):
    """V2MonitoringExtranetStatusDetailsGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2MonitoringExtranetStatusDetailsGetRequest:
        """Test V2MonitoringExtranetStatusDetailsGetRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2MonitoringExtranetStatusDetailsGetRequest`
        """
        model = V2MonitoringExtranetStatusDetailsGetRequest()
        if include_optional:
            return V2MonitoringExtranetStatusDetailsGetRequest(
                id = 1234567891011,
                is_b2_b = True,
                is_provider = True,
                server_address = 'example string',
                service_id = 1234567891011,
                site_id = 1234567891011
            )
        else:
            return V2MonitoringExtranetStatusDetailsGetRequest(
        )
        """

    def testV2MonitoringExtranetStatusDetailsGetRequest(self):
        """Test V2MonitoringExtranetStatusDetailsGetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
