# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.ipfix_app_bandwidth_stats import IpfixAppBandwidthStats

class TestIpfixAppBandwidthStats(unittest.TestCase):
    """IpfixAppBandwidthStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IpfixAppBandwidthStats:
        """Test IpfixAppBandwidthStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IpfixAppBandwidthStats`
        """
        model = IpfixAppBandwidthStats()
        if include_optional:
            return IpfixAppBandwidthStats(
                dl_bw = 123.45,
                ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, ),
                ul_bw = 123.45
            )
        else:
            return IpfixAppBandwidthStats(
        )
        """

    def testIpfixAppBandwidthStats(self):
        """Test IpfixAppBandwidthStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
