# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_bwtracker_region_edge_summary_post_response import V1BwtrackerRegionEdgeSummaryPostResponse

class TestV1BwtrackerRegionEdgeSummaryPostResponse(unittest.TestCase):
    """V1BwtrackerRegionEdgeSummaryPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1BwtrackerRegionEdgeSummaryPostResponse:
        """Test V1BwtrackerRegionEdgeSummaryPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1BwtrackerRegionEdgeSummaryPostResponse`
        """
        model = V1BwtrackerRegionEdgeSummaryPostResponse()
        if include_optional:
            return V1BwtrackerRegionEdgeSummaryPostResponse(
                bwusage_summary = graphiant_sdk.models.statsmon_bandwidthtracker_bw_usage_by_region_edge_summary.statsmonBandwidthtrackerBwUsageByRegionEdgeSummary(
                    bwusage_top_sites = [
                        graphiant_sdk.models.statsmon_bandwidthtracker_bw_usage_by_top_sites.statsmonBandwidthtrackerBwUsageByTopSites(
                            site_id = 12345678910, 
                            site_name = 'example string', 
                            usage_kbps = 123.45, )
                        ], 
                    edgeusage_kbps = 123.45, 
                    percent_changed = 123.45, 
                    site_count = 12345678910, 
                    totusage_kbps = 123.45, )
            )
        else:
            return V1BwtrackerRegionEdgeSummaryPostResponse(
        )
        """

    def testV1BwtrackerRegionEdgeSummaryPostResponse(self):
        """Test V1BwtrackerRegionEdgeSummaryPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
