# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.iam_counts import IamCounts

class TestIamCounts(unittest.TestCase):
    """IamCounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IamCounts:
        """Test IamCounts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IamCounts`
        """
        model = IamCounts()
        if include_optional:
            return IamCounts(
                active_down_count = 1234567891011,
                active_up_count = 1234567891011,
                deactivated_down_count = 1234567891011,
                down_sites_count = 1234567891011,
                empty_sites_count = 1234567891011,
                impaired_sites_count = 1234567891011,
                staging_down_count = 1234567891011,
                staging_up_count = 1234567891011,
                total_customers = 1234567891011,
                total_edges = 1234567891011,
                total_msps = 1234567891011,
                total_sites = 1234567891011,
                up_sites_count = 1234567891011
            )
        else:
            return IamCounts(
        )
        """

    def testIamCounts(self):
        """Test IamCounts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
