# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_gateways_ipsec_regions_region_id_vrfs_vrf_id_inside_subnet_get_response import V1GatewaysIpsecRegionsRegionIdVrfsVrfIdInsideSubnetGetResponse

class TestV1GatewaysIpsecRegionsRegionIdVrfsVrfIdInsideSubnetGetResponse(unittest.TestCase):
    """V1GatewaysIpsecRegionsRegionIdVrfsVrfIdInsideSubnetGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GatewaysIpsecRegionsRegionIdVrfsVrfIdInsideSubnetGetResponse:
        """Test V1GatewaysIpsecRegionsRegionIdVrfsVrfIdInsideSubnetGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GatewaysIpsecRegionsRegionIdVrfsVrfIdInsideSubnetGetResponse`
        """
        model = V1GatewaysIpsecRegionsRegionIdVrfsVrfIdInsideSubnetGetResponse()
        if include_optional:
            return V1GatewaysIpsecRegionsRegionIdVrfsVrfIdInsideSubnetGetResponse(
                ipv4_subnet = 'example string',
                ipv6_subnet = 'example string'
            )
        else:
            return V1GatewaysIpsecRegionsRegionIdVrfsVrfIdInsideSubnetGetResponse(
        )
        """

    def testV1GatewaysIpsecRegionsRegionIdVrfsVrfIdInsideSubnetGetResponse(self):
        """Test V1GatewaysIpsecRegionsRegionIdVrfsVrfIdInsideSubnetGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
