# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_monitoring_ipsec_post_response import V2MonitoringIpsecPostResponse

class TestV2MonitoringIpsecPostResponse(unittest.TestCase):
    """V2MonitoringIpsecPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2MonitoringIpsecPostResponse:
        """Test V2MonitoringIpsecPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2MonitoringIpsecPostResponse`
        """
        model = V2MonitoringIpsecPostResponse()
        if include_optional:
            return V2MonitoringIpsecPostResponse(
                data = [
                    graphiant_sdk.models.v2_monitoring_ipsec_post_response_data.v2MonitoringIpsecPostResponseData(
                        samples = [
                            graphiant_sdk.models.statsmon_v2_stats_sample.statsmonV2StatsSample(
                                status = 'ENUM_VALUE', 
                                ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                                    nanos = 123, 
                                    seconds = 1234567891011, ), 
                                value = 123.45, )
                            ], 
                        selector = graphiant_sdk.models.statsmon_v2_ip_sec_stats_selector.statsmonV2IpSecStatsSelector(
                            peer_gdi = 'example string', 
                            type = 'ENUM_VALUE', ), )
                    ]
            )
        else:
            return V2MonitoringIpsecPostResponse(
        )
        """

    def testV2MonitoringIpsecPostResponse(self):
        """Test V2MonitoringIpsecPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
