# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.syslogmon_histogram import SyslogmonHistogram

class TestSyslogmonHistogram(unittest.TestCase):
    """SyslogmonHistogram unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyslogmonHistogram:
        """Test SyslogmonHistogram
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyslogmonHistogram`
        """
        model = SyslogmonHistogram()
        if include_optional:
            return SyslogmonHistogram(
                count = 123,
                ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, )
            )
        else:
            return SyslogmonHistogram(
        )
        """

    def testSyslogmonHistogram(self):
        """Test SyslogmonHistogram"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
