# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.assurance_application_profile_summary import AssuranceApplicationProfileSummary

class TestAssuranceApplicationProfileSummary(unittest.TestCase):
    """AssuranceApplicationProfileSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssuranceApplicationProfileSummary:
        """Test AssuranceApplicationProfileSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssuranceApplicationProfileSummary`
        """
        model = AssuranceApplicationProfileSummary()
        if include_optional:
            return AssuranceApplicationProfileSummary(
                bucket_summary_list = [
                    graphiant_sdk.models.assurance_bucket_summary.assuranceBucketSummary(
                        assurance_bucket = 'ENUM_VALUE', 
                        bucket_color = 'ENUM_VALUE', 
                        bucket_name_to_display = 'example string', 
                        bucket_stats = graphiant_sdk.models.assurance_bucket_stats.assuranceBucketStats(
                            prev_unique_app_count = 1234567891011, 
                            prev_unique_threat_count = 1234567891011, 
                            unique_app_count = 1234567891011, 
                            unique_threat_count = 1234567891011, ), 
                        child_bucket_list = [
                            'ENUM_VALUE'
                            ], 
                        child_bucket_stats_list = [
                            graphiant_sdk.models.assurance_bucket_stats_with_id.assuranceBucketStatsWithId(
                                assurance_bucket = 'ENUM_VALUE', 
                                bucket_name_to_display = 'example string', 
                                prev_unique_app_count = 1234567891011, 
                                unique_app_count = 1234567891011, )
                            ], 
                        is_root = True, 
                        is_terminal = True, 
                        parent_bucket_list = [
                            'ENUM_VALUE'
                            ], )
                    ]
            )
        else:
            return AssuranceApplicationProfileSummary(
        )
        """

    def testAssuranceApplicationProfileSummary(self):
        """Test AssuranceApplicationProfileSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
