# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_vrrp_group_interface_priority_decrement import ManaV2VRRPGroupInterfacePriorityDecrement

class TestManaV2VRRPGroupInterfacePriorityDecrement(unittest.TestCase):
    """ManaV2VRRPGroupInterfacePriorityDecrement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2VRRPGroupInterfacePriorityDecrement:
        """Test ManaV2VRRPGroupInterfacePriorityDecrement
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2VRRPGroupInterfacePriorityDecrement`
        """
        model = ManaV2VRRPGroupInterfacePriorityDecrement()
        if include_optional:
            return ManaV2VRRPGroupInterfacePriorityDecrement(
                interface = 'example string',
                priority_decrement = 123
            )
        else:
            return ManaV2VRRPGroupInterfacePriorityDecrement(
        )
        """

    def testManaV2VRRPGroupInterfacePriorityDecrement(self):
        """Test ManaV2VRRPGroupInterfacePriorityDecrement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
