# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_b2b_extranet_application_invite import ManaV2B2bExtranetApplicationInvite

class TestManaV2B2bExtranetApplicationInvite(unittest.TestCase):
    """ManaV2B2bExtranetApplicationInvite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2B2bExtranetApplicationInvite:
        """Test ManaV2B2bExtranetApplicationInvite
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2B2bExtranetApplicationInvite`
        """
        model = ManaV2B2bExtranetApplicationInvite()
        if include_optional:
            return ManaV2B2bExtranetApplicationInvite(
                admin_email = 'example string',
                consumer_burst_size = 123,
                consumer_bw_site = 123,
                enterprise_id = 1234567891011,
                maximum_site_count = 123,
                service_prefixes = [
                    'example string'
                    ]
            )
        else:
            return ManaV2B2bExtranetApplicationInvite(
        )
        """

    def testManaV2B2bExtranetApplicationInvite(self):
        """Test ManaV2B2bExtranetApplicationInvite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
