# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_lldp_interface_id_summary_get_response import V1LldpInterfaceIdSummaryGetResponse

class TestV1LldpInterfaceIdSummaryGetResponse(unittest.TestCase):
    """V1LldpInterfaceIdSummaryGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1LldpInterfaceIdSummaryGetResponse:
        """Test V1LldpInterfaceIdSummaryGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1LldpInterfaceIdSummaryGetResponse`
        """
        model = V1LldpInterfaceIdSummaryGetResponse()
        if include_optional:
            return V1LldpInterfaceIdSummaryGetResponse(
                num_neighbors = 1234567891011,
                num_vendors = 1234567891011
            )
        else:
            return V1LldpInterfaceIdSummaryGetResponse(
        )
        """

    def testV1LldpInterfaceIdSummaryGetResponse(self):
        """Test V1LldpInterfaceIdSummaryGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
