# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_device_routing_ospfv3_statistics_get_response import V1DeviceRoutingOspfv3StatisticsGetResponse

class TestV1DeviceRoutingOspfv3StatisticsGetResponse(unittest.TestCase):
    """V1DeviceRoutingOspfv3StatisticsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DeviceRoutingOspfv3StatisticsGetResponse:
        """Test V1DeviceRoutingOspfv3StatisticsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DeviceRoutingOspfv3StatisticsGetResponse`
        """
        model = V1DeviceRoutingOspfv3StatisticsGetResponse()
        if include_optional:
            return V1DeviceRoutingOspfv3StatisticsGetResponse(
                statistics = {
                    'key' : graphiant_sdk.models.routing_ospf_statistics.routingOspfStatistics(
                        discontinuity_time = 'example string', 
                        route_count = 123, )
                    }
            )
        else:
            return V1DeviceRoutingOspfv3StatisticsGetResponse(
        )
        """

    def testV1DeviceRoutingOspfv3StatisticsGetResponse(self):
        """Test V1DeviceRoutingOspfv3StatisticsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
