# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_extranet_consumers_usage_top_post_response import V2ExtranetConsumersUsageTopPostResponse

class TestV2ExtranetConsumersUsageTopPostResponse(unittest.TestCase):
    """V2ExtranetConsumersUsageTopPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2ExtranetConsumersUsageTopPostResponse:
        """Test V2ExtranetConsumersUsageTopPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2ExtranetConsumersUsageTopPostResponse`
        """
        model = V2ExtranetConsumersUsageTopPostResponse()
        if include_optional:
            return V2ExtranetConsumersUsageTopPostResponse(
                top_consumers = [
                    graphiant_sdk.models.ipfix_entity_usage.ipfixEntityUsage(
                        id = 1234567891011, 
                        name = 'example string', 
                        usage = 123.45, )
                    ],
                total_customers = 1234567891011,
                total_usage = 123.45
            )
        else:
            return V2ExtranetConsumersUsageTopPostResponse(
        )
        """

    def testV2ExtranetConsumersUsageTopPostResponse(self):
        """Test V2ExtranetConsumersUsageTopPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
