# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_global_site_status_get_request import V1GlobalSiteStatusGetRequest

class TestV1GlobalSiteStatusGetRequest(unittest.TestCase):
    """V1GlobalSiteStatusGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GlobalSiteStatusGetRequest:
        """Test V1GlobalSiteStatusGetRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GlobalSiteStatusGetRequest`
        """
        model = V1GlobalSiteStatusGetRequest()
        if include_optional:
            return V1GlobalSiteStatusGetRequest(
                ipfix_exported_site_id = 1234567891011,
                prefix_set_site_id = 1234567891011,
                routing_policy_site_id = 1234567891011,
                snmp_site_id = 1234567891011,
                syslog_server_site_id = 1234567891011,
                traffic_policy_site_id = 1234567891011
            )
        else:
            return V1GlobalSiteStatusGetRequest(
        )
        """

    def testV1GlobalSiteStatusGetRequest(self):
        """Test V1GlobalSiteStatusGetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
