# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_devices_device_id_ospfv3_default_originate_get_request import V1DevicesDeviceIdOspfv3DefaultOriginateGetRequest

class TestV1DevicesDeviceIdOspfv3DefaultOriginateGetRequest(unittest.TestCase):
    """V1DevicesDeviceIdOspfv3DefaultOriginateGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DevicesDeviceIdOspfv3DefaultOriginateGetRequest:
        """Test V1DevicesDeviceIdOspfv3DefaultOriginateGetRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DevicesDeviceIdOspfv3DefaultOriginateGetRequest`
        """
        model = V1DevicesDeviceIdOspfv3DefaultOriginateGetRequest()
        if include_optional:
            return V1DevicesDeviceIdOspfv3DefaultOriginateGetRequest(
                vrf_names = [
                    'example string'
                    ]
            )
        else:
            return V1DevicesDeviceIdOspfv3DefaultOriginateGetRequest(
        )
        """

    def testV1DevicesDeviceIdOspfv3DefaultOriginateGetRequest(self):
        """Test V1DevicesDeviceIdOspfv3DefaultOriginateGetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
