# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranets_b2b_peering_consumer_id_prefixes_put_request import V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest

class TestV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest(unittest.TestCase):
    """V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest:
        """Test V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest`
        """
        model = V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest()
        if include_optional:
            return V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest(
                service_prefixes = [
                    graphiant_sdk.models.mana_v2_b2b_nat.manaV2B2bNat(
                        outside_nat_prefix = '100.1.2.0/24', 
                        prefix = '10.1.2.0/24', )
                    ]
            )
        else:
            return V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest(
                service_prefixes = [
                    graphiant_sdk.models.mana_v2_b2b_nat.manaV2B2bNat(
                        outside_nat_prefix = '100.1.2.0/24', 
                        prefix = '10.1.2.0/24', )
                    ],
        )
        """

    def testV1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest(self):
        """Test V1ExtranetsB2bPeeringConsumerIdPrefixesPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
