# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_assurance_topology_inventory_post_response import V2AssuranceTopologyInventoryPostResponse

class TestV2AssuranceTopologyInventoryPostResponse(unittest.TestCase):
    """V2AssuranceTopologyInventoryPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2AssuranceTopologyInventoryPostResponse:
        """Test V2AssuranceTopologyInventoryPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2AssuranceTopologyInventoryPostResponse`
        """
        model = V2AssuranceTopologyInventoryPostResponse()
        if include_optional:
            return V2AssuranceTopologyInventoryPostResponse(
                app_names = [
                    'example string'
                    ],
                client_sites = [
                    graphiant_sdk.models.assurance_site.assuranceSite(
                        region_id = 123, 
                        site_id = 1234567891011, 
                        site_name = 'example string', )
                    ],
                regions = [
                    graphiant_sdk.models.assurance_region.assuranceRegion(
                        region_id = 123, 
                        region_name = 'example string', )
                    ],
                server_sites = [
                    graphiant_sdk.models.assurance_site.assuranceSite(
                        region_id = 123, 
                        site_id = 1234567891011, 
                        site_name = 'example string', )
                    ],
                topology_change_ts = [
                    graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                        nanos = 123, 
                        seconds = 1234567891011, )
                    ]
            )
        else:
            return V2AssuranceTopologyInventoryPostResponse(
        )
        """

    def testV2AssuranceTopologyInventoryPostResponse(self):
        """Test V2AssuranceTopologyInventoryPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
