# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_sdk_automation_playbook_configs_config_id_get_response import V1SdkAutomationPlaybookConfigsConfigIdGetResponse

class TestV1SdkAutomationPlaybookConfigsConfigIdGetResponse(unittest.TestCase):
    """V1SdkAutomationPlaybookConfigsConfigIdGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SdkAutomationPlaybookConfigsConfigIdGetResponse:
        """Test V1SdkAutomationPlaybookConfigsConfigIdGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SdkAutomationPlaybookConfigsConfigIdGetResponse`
        """
        model = V1SdkAutomationPlaybookConfigsConfigIdGetResponse()
        if include_optional:
            return V1SdkAutomationPlaybookConfigsConfigIdGetResponse(
                config = graphiant_sdk.models.sdk_automation_playbook_config.sdkAutomationPlaybookConfig(
                    bundle_key = 'example string', 
                    config_id = 'example string', 
                    created_by_user_id = 'example string', 
                    description = 'example string', 
                    files = [
                        graphiant_sdk.models.sdk_automation_module_file.sdkAutomationModuleFile(
                            content = 'example string', 
                            filename = 'example string', 
                            module_key = 'example string', )
                        ], 
                    name = 'example string', 
                    status = 'ENUM_VALUE', )
            )
        else:
            return V1SdkAutomationPlaybookConfigsConfigIdGetResponse(
        )
        """

    def testV1SdkAutomationPlaybookConfigsConfigIdGetResponse(self):
        """Test V1SdkAutomationPlaybookConfigsConfigIdGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
