# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.routing_nd_entry import RoutingNdEntry

class TestRoutingNdEntry(unittest.TestCase):
    """RoutingNdEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoutingNdEntry:
        """Test RoutingNdEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoutingNdEntry`
        """
        model = RoutingNdEntry()
        if include_optional:
            return RoutingNdEntry(
                interface_name = 'example string',
                ipv6_address = 'example string',
                mac_address = 'example string',
                name = 'example string'
            )
        else:
            return RoutingNdEntry(
        )
        """

    def testRoutingNdEntry(self):
        """Test RoutingNdEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
