# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_nullable_ospf_retransmit_interval_value import ManaV2NullableOspfRetransmitIntervalValue

class TestManaV2NullableOspfRetransmitIntervalValue(unittest.TestCase):
    """ManaV2NullableOspfRetransmitIntervalValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2NullableOspfRetransmitIntervalValue:
        """Test ManaV2NullableOspfRetransmitIntervalValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2NullableOspfRetransmitIntervalValue`
        """
        model = ManaV2NullableOspfRetransmitIntervalValue()
        if include_optional:
            return ManaV2NullableOspfRetransmitIntervalValue(
                retransmit_interval = 123
            )
        else:
            return ManaV2NullableOspfRetransmitIntervalValue(
        )
        """

    def testManaV2NullableOspfRetransmitIntervalValue(self):
        """Test ManaV2NullableOspfRetransmitIntervalValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
