# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_global_ipfix_site_get_response import V1GlobalIpfixSiteGetResponse

class TestV1GlobalIpfixSiteGetResponse(unittest.TestCase):
    """V1GlobalIpfixSiteGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GlobalIpfixSiteGetResponse:
        """Test V1GlobalIpfixSiteGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GlobalIpfixSiteGetResponse`
        """
        model = V1GlobalIpfixSiteGetResponse()
        if include_optional:
            return V1GlobalIpfixSiteGetResponse(
                exporters = [
                    graphiant_sdk.models.mana_v2_ipfix_exporter.manaV2IpfixExporter(
                        destination_address = 'example string', 
                        destination_port = 123, 
                        error_message = 'example string', 
                        global_id = 1234567891011, 
                        id = 1234567891011, 
                        monitored_segments = [
                            'example string'
                            ], 
                        name = 'example string', 
                        sample_mode = 'example string', 
                        sample_rate = 1234567891011, 
                        source_address = 'example string', 
                        source_interface = 'example string', 
                        source_segment = 'example string', 
                        status = 'ENUM_VALUE', 
                        vrf_id = 1234567891011, 
                        vrf_name = 'example string', )
                    ]
            )
        else:
            return V1GlobalIpfixSiteGetResponse(
        )
        """

    def testV1GlobalIpfixSiteGetResponse(self):
        """Test V1GlobalIpfixSiteGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
