# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranets_b2b_peering_match_service_to_customer_id_get_request import V1ExtranetsB2bPeeringMatchServiceToCustomerIdGetRequest

class TestV1ExtranetsB2bPeeringMatchServiceToCustomerIdGetRequest(unittest.TestCase):
    """V1ExtranetsB2bPeeringMatchServiceToCustomerIdGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetsB2bPeeringMatchServiceToCustomerIdGetRequest:
        """Test V1ExtranetsB2bPeeringMatchServiceToCustomerIdGetRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetsB2bPeeringMatchServiceToCustomerIdGetRequest`
        """
        model = V1ExtranetsB2bPeeringMatchServiceToCustomerIdGetRequest()
        if include_optional:
            return V1ExtranetsB2bPeeringMatchServiceToCustomerIdGetRequest(
                customer_id = 1234567891011
            )
        else:
            return V1ExtranetsB2bPeeringMatchServiceToCustomerIdGetRequest(
                customer_id = 1234567891011,
        )
        """

    def testV1ExtranetsB2bPeeringMatchServiceToCustomerIdGetRequest(self):
        """Test V1ExtranetsB2bPeeringMatchServiceToCustomerIdGetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
