# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_policy_route_tag_sets_tags_get_response import V1PolicyRouteTagSetsTagsGetResponse

class TestV1PolicyRouteTagSetsTagsGetResponse(unittest.TestCase):
    """V1PolicyRouteTagSetsTagsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1PolicyRouteTagSetsTagsGetResponse:
        """Test V1PolicyRouteTagSetsTagsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1PolicyRouteTagSetsTagsGetResponse`
        """
        model = V1PolicyRouteTagSetsTagsGetResponse()
        if include_optional:
            return V1PolicyRouteTagSetsTagsGetResponse(
                tags = [
                    graphiant_sdk.models.mana_v2_route_tag_element.manaV2RouteTagElement(
                        id = 1234567891011, 
                        next_set = [
                            graphiant_sdk.models.mana_v2_route_tag_element.manaV2RouteTagElement(
                                id = 1234567891011, 
                                tag = 'example string', 
                                tag_value = 123, )
                            ], 
                        tag = 'example string', 
                        tag_value = 123, )
                    ]
            )
        else:
            return V1PolicyRouteTagSetsTagsGetResponse(
        )
        """

    def testV1PolicyRouteTagSetsTagsGetResponse(self):
        """Test V1PolicyRouteTagSetsTagsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
