# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_dns import ManaV2Dns

class TestManaV2Dns(unittest.TestCase):
    """ManaV2Dns unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2Dns:
        """Test ManaV2Dns
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2Dns`
        """
        model = ManaV2Dns()
        if include_optional:
            return ManaV2Dns(
                cloudflare_servers = [
                    graphiant_sdk.models.mana_v2_dnsip_address.manaV2DnsipAddress(
                        circuit_name = 'example string', 
                        interface_name = 'example string', 
                        ipv4 = 'example string', 
                        ipv6 = 'example string', 
                        source = 'example string', 
                        stale = True, 
                        type = 'ENUM_VALUE', )
                    ],
                dynamic_servers = [
                    graphiant_sdk.models.mana_v2_dnsip_address.manaV2DnsipAddress(
                        circuit_name = 'example string', 
                        interface_name = 'example string', 
                        ipv4 = 'example string', 
                        ipv6 = 'example string', 
                        source = 'example string', 
                        stale = True, 
                        type = 'ENUM_VALUE', )
                    ],
                dynamic_servers_v2 = graphiant_sdk.models.mana_v2_dynamic_dns_servers.manaV2DynamicDnsServers(
                    circuit = 'example string', 
                    servers = {
                        'key' : graphiant_sdk.models.mana_v2_dnsip_addresses.manaV2DnsipAddresses(
                            dynamic_servers = [
                                graphiant_sdk.models.mana_v2_dnsip_address.manaV2DnsipAddress(
                                    circuit_name = 'example string', 
                                    interface_name = 'example string', 
                                    ipv4 = 'example string', 
                                    ipv6 = 'example string', 
                                    source = 'example string', 
                                    stale = True, 
                                    type = 'ENUM_VALUE', )
                                ], )
                        }, ),
                mode = 'ENUM_VALUE',
                static_servers = [
                    graphiant_sdk.models.mana_v2_dnsip_address.manaV2DnsipAddress(
                        circuit_name = 'example string', 
                        interface_name = 'example string', 
                        ipv4 = 'example string', 
                        ipv6 = 'example string', 
                        source = 'example string', 
                        stale = True, 
                        type = 'ENUM_VALUE', )
                    ],
                static_servers_v2 = graphiant_sdk.models.mana_v2_static_dns_servers.manaV2StaticDnsServers(
                    primary_ipv4_server = graphiant_sdk.models.mana_v2_dnsip_address.manaV2DnsipAddress(
                        circuit_name = 'example string', 
                        interface_name = 'example string', 
                        ipv4 = 'example string', 
                        ipv6 = 'example string', 
                        source = 'example string', 
                        stale = True, 
                        type = 'ENUM_VALUE', ), 
                    primary_ipv6_server = graphiant_sdk.models.mana_v2_dnsip_address.manaV2DnsipAddress(
                        circuit_name = 'example string', 
                        interface_name = 'example string', 
                        ipv4 = 'example string', 
                        ipv6 = 'example string', 
                        source = 'example string', 
                        stale = True, 
                        type = 'ENUM_VALUE', ), 
                    secondary_ipv4_server = , 
                    secondary_ipv6_server = , )
            )
        else:
            return ManaV2Dns(
        )
        """

    def testManaV2Dns(self):
        """Test ManaV2Dns"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
