# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_assurance_topology_inventory_post_request import V2AssuranceTopologyInventoryPostRequest

class TestV2AssuranceTopologyInventoryPostRequest(unittest.TestCase):
    """V2AssuranceTopologyInventoryPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2AssuranceTopologyInventoryPostRequest:
        """Test V2AssuranceTopologyInventoryPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2AssuranceTopologyInventoryPostRequest`
        """
        model = V2AssuranceTopologyInventoryPostRequest()
        if include_optional:
            return V2AssuranceTopologyInventoryPostRequest(
                bucket_id = 'ENUM_VALUE',
                time_window = graphiant_sdk.models.assurance_time_window.assuranceTimeWindow(
                    bucket_size_sec = 123, 
                    old_ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                        nanos = 123, 
                        seconds = 1234567891011, ), 
                    recent_ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                        nanos = 123, 
                        seconds = 1234567891011, ), ),
                topology_type = 'ENUM_VALUE'
            )
        else:
            return V2AssuranceTopologyInventoryPostRequest(
        )
        """

    def testV2AssuranceTopologyInventoryPostRequest(self):
        """Test V2AssuranceTopologyInventoryPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
