# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_gateways_reference_consumer_get_request import V1GatewaysReferenceConsumerGetRequest

class TestV1GatewaysReferenceConsumerGetRequest(unittest.TestCase):
    """V1GatewaysReferenceConsumerGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GatewaysReferenceConsumerGetRequest:
        """Test V1GatewaysReferenceConsumerGetRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GatewaysReferenceConsumerGetRequest`
        """
        model = V1GatewaysReferenceConsumerGetRequest()
        if include_optional:
            return V1GatewaysReferenceConsumerGetRequest(
                customer_id = 1234567891011,
                lan_segment_id = 1234567891011,
                region_id = 123
            )
        else:
            return V1GatewaysReferenceConsumerGetRequest(
        )
        """

    def testV1GatewaysReferenceConsumerGetRequest(self):
        """Test V1GatewaysReferenceConsumerGetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
