# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_groups_id_enterprises_enterprise_id_delete_response import V1GroupsIdEnterprisesEnterpriseIdDeleteResponse

class TestV1GroupsIdEnterprisesEnterpriseIdDeleteResponse(unittest.TestCase):
    """V1GroupsIdEnterprisesEnterpriseIdDeleteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GroupsIdEnterprisesEnterpriseIdDeleteResponse:
        """Test V1GroupsIdEnterprisesEnterpriseIdDeleteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GroupsIdEnterprisesEnterpriseIdDeleteResponse`
        """
        model = V1GroupsIdEnterprisesEnterpriseIdDeleteResponse()
        if include_optional:
            return V1GroupsIdEnterprisesEnterpriseIdDeleteResponse(
                affected_users = [
                    'example string'
                    ],
                enterprise_group = True
            )
        else:
            return V1GroupsIdEnterprisesEnterpriseIdDeleteResponse(
        )
        """

    def testV1GroupsIdEnterprisesEnterpriseIdDeleteResponse(self):
        """Test V1GroupsIdEnterprisesEnterpriseIdDeleteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
