# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_device_routing_ospfv3_area_interface_get_request import V1DeviceRoutingOspfv3AreaInterfaceGetRequest

class TestV1DeviceRoutingOspfv3AreaInterfaceGetRequest(unittest.TestCase):
    """V1DeviceRoutingOspfv3AreaInterfaceGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DeviceRoutingOspfv3AreaInterfaceGetRequest:
        """Test V1DeviceRoutingOspfv3AreaInterfaceGetRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DeviceRoutingOspfv3AreaInterfaceGetRequest`
        """
        model = V1DeviceRoutingOspfv3AreaInterfaceGetRequest()
        if include_optional:
            return V1DeviceRoutingOspfv3AreaInterfaceGetRequest(
                page_request = graphiant_sdk.models.common_page_request.commonPageRequest(
                    after = 'example string', 
                    before = 'example string', 
                    first = 123, 
                    last = 123, 
                    token = 'example string', )
            )
        else:
            return V1DeviceRoutingOspfv3AreaInterfaceGetRequest(
        )
        """

    def testV1DeviceRoutingOspfv3AreaInterfaceGetRequest(self):
        """Test V1DeviceRoutingOspfv3AreaInterfaceGetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
