# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_global_attached_edges_post_request import V1GlobalAttachedEdgesPostRequest

class TestV1GlobalAttachedEdgesPostRequest(unittest.TestCase):
    """V1GlobalAttachedEdgesPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GlobalAttachedEdgesPostRequest:
        """Test V1GlobalAttachedEdgesPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GlobalAttachedEdgesPostRequest`
        """
        model = V1GlobalAttachedEdgesPostRequest()
        if include_optional:
            return V1GlobalAttachedEdgesPostRequest(
                ipfix_exported_ids = [
                    1234567891011
                    ],
                prefix_set_ids = [
                    1234567891011
                    ],
                routing_policy_ids = [
                    1234567891011
                    ],
                snmp_ids = [
                    1234567891011
                    ],
                syslog_server_ids = [
                    1234567891011
                    ],
                traffic_policy_ids = [
                    1234567891011
                    ]
            )
        else:
            return V1GlobalAttachedEdgesPostRequest(
        )
        """

    def testV1GlobalAttachedEdgesPostRequest(self):
        """Test V1GlobalAttachedEdgesPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
