# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_bgp_neighbor import ManaV2BgpNeighbor

class TestManaV2BgpNeighbor(unittest.TestCase):
    """ManaV2BgpNeighbor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2BgpNeighbor:
        """Test ManaV2BgpNeighbor
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2BgpNeighbor`
        """
        model = ManaV2BgpNeighbor()
        if include_optional:
            return ManaV2BgpNeighbor(
                address_families = [
                    graphiant_sdk.models.mana_v2_bgp_neighbor_address_family.manaV2BgpNeighborAddressFamily(
                        address_family = 'ENUM_VALUE', 
                        id = 1234567891011, 
                        inbound_policy = 'example string', 
                        outbound_policy = 'example string', )
                    ],
                allow_as_in = 123,
                as_override = True,
                bfd = graphiant_sdk.models.mana_v2_bfd_instance.manaV2BfdInstance(
                    enabled = True, 
                    minimum_interval = 123, 
                    multiplier = 123, ),
                bfd_neighbor = graphiant_sdk.models.mana_v2_bfd_neighbor.manaV2BfdNeighbor(
                    desired_minimum_tx_interval = 123, 
                    if_index = 123, 
                    interface = 'example string', 
                    last_updated = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                        nanos = 123, 
                        seconds = 1234567891011, ), 
                    local_diag = 'ENUM_VALUE', 
                    peer_address = 'example string', 
                    remote_diag = 'ENUM_VALUE', 
                    required_minimum_rx_interval = 123, 
                    segment_name = 'example string', 
                    source_address = 'example string', 
                    state = 'ENUM_VALUE', 
                    time_in_state = graphiant_sdk.models.google_protobuf_duration.googleProtobufDuration(
                        nanos = 123, 
                        seconds = 1234567891011, ), 
                    up = True, ),
                bgp_type = 'ENUM_VALUE',
                default_originate = 'ENUM_VALUE',
                enabled = True,
                hold_timer = 123,
                id = 1234567891011,
                keepalive_timer = 123,
                local_address = 'example string',
                local_interface = 'example string',
                max_prefix = 10000,
                md5_password = 'example string',
                multi_hop = 5,
                peer_asn = 123,
                remote_address = 'example string',
                remove_private_as = True,
                send_community = False,
                state = 'ENUM_VALUE',
                time_since_last_oper_change = graphiant_sdk.models.google_protobuf_duration.googleProtobufDuration(
                    nanos = 123, 
                    seconds = 1234567891011, ),
                up = True
            )
        else:
            return ManaV2BgpNeighbor(
        )
        """

    def testManaV2BgpNeighbor(self):
        """Test ManaV2BgpNeighbor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
