# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_nullable_sla_conformance import ManaV2NullableSlaConformance

class TestManaV2NullableSlaConformance(unittest.TestCase):
    """ManaV2NullableSlaConformance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2NullableSlaConformance:
        """Test ManaV2NullableSlaConformance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2NullableSlaConformance`
        """
        model = ManaV2NullableSlaConformance()
        if include_optional:
            return ManaV2NullableSlaConformance(
                sla_conformance = graphiant_sdk.models.mana_v2_sla_conformance.manaV2SlaConformance(
                    dampening_factor = 1234567891011, 
                    duration = 1234567891011, 
                    interval = 1234567891011, )
            )
        else:
            return ManaV2NullableSlaConformance(
        )
        """

    def testManaV2NullableSlaConformance(self):
        """Test ManaV2NullableSlaConformance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
