# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_circuit_interface import ManaV2CircuitInterface

class TestManaV2CircuitInterface(unittest.TestCase):
    """ManaV2CircuitInterface unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2CircuitInterface:
        """Test ManaV2CircuitInterface
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2CircuitInterface`
        """
        model = ManaV2CircuitInterface()
        if include_optional:
            return ManaV2CircuitInterface(
                admin_status = True,
                id = 1234567891011,
                index = 1234567891011,
                name = 'example string',
                oper_status = True
            )
        else:
            return ManaV2CircuitInterface(
        )
        """

    def testManaV2CircuitInterface(self):
        """Test ManaV2CircuitInterface"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
