# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_data_assurance_assurances_global_get_response_row_app_entry import V1DataAssuranceAssurancesGlobalGetResponseRowAppEntry

class TestV1DataAssuranceAssurancesGlobalGetResponseRowAppEntry(unittest.TestCase):
    """V1DataAssuranceAssurancesGlobalGetResponseRowAppEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DataAssuranceAssurancesGlobalGetResponseRowAppEntry:
        """Test V1DataAssuranceAssurancesGlobalGetResponseRowAppEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DataAssuranceAssurancesGlobalGetResponseRowAppEntry`
        """
        model = V1DataAssuranceAssurancesGlobalGetResponseRowAppEntry()
        if include_optional:
            return V1DataAssuranceAssurancesGlobalGetResponseRowAppEntry(
                app_name = 'example string'
            )
        else:
            return V1DataAssuranceAssurancesGlobalGetResponseRowAppEntry(
        )
        """

    def testV1DataAssuranceAssurancesGlobalGetResponseRowAppEntry(self):
        """Test V1DataAssuranceAssurancesGlobalGetResponseRowAppEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
