# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_customer_match_info import ManaV2CustomerMatchInfo

class TestManaV2CustomerMatchInfo(unittest.TestCase):
    """ManaV2CustomerMatchInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2CustomerMatchInfo:
        """Test ManaV2CustomerMatchInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2CustomerMatchInfo`
        """
        model = ManaV2CustomerMatchInfo()
        if include_optional:
            return ManaV2CustomerMatchInfo(
                customer_id = 'example string',
                customer_name = 'example string',
                emails = [
                    'example string'
                    ],
                match_id = 1234567891011,
                matched_services = 123,
                peer_type = 'ENUM_VALUE',
                status = 'ENUM_VALUE',
                updated_at = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, )
            )
        else:
            return ManaV2CustomerMatchInfo(
        )
        """

    def testManaV2CustomerMatchInfo(self):
        """Test ManaV2CustomerMatchInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
