# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_extranets_monitoring_consumers_post_request import V2ExtranetsMonitoringConsumersPostRequest

class TestV2ExtranetsMonitoringConsumersPostRequest(unittest.TestCase):
    """V2ExtranetsMonitoringConsumersPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2ExtranetsMonitoringConsumersPostRequest:
        """Test V2ExtranetsMonitoringConsumersPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2ExtranetsMonitoringConsumersPostRequest`
        """
        model = V2ExtranetsMonitoringConsumersPostRequest()
        if include_optional:
            return V2ExtranetsMonitoringConsumersPostRequest(
                id = 1234567891011
            )
        else:
            return V2ExtranetsMonitoringConsumersPostRequest(
        )
        """

    def testV2ExtranetsMonitoringConsumersPostRequest(self):
        """Test V2ExtranetsMonitoringConsumersPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
