# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_diagnostic_clear_arp_device_id_put_request import V1DiagnosticClearArpDeviceIdPutRequest

class TestV1DiagnosticClearArpDeviceIdPutRequest(unittest.TestCase):
    """V1DiagnosticClearArpDeviceIdPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DiagnosticClearArpDeviceIdPutRequest:
        """Test V1DiagnosticClearArpDeviceIdPutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DiagnosticClearArpDeviceIdPutRequest`
        """
        model = V1DiagnosticClearArpDeviceIdPutRequest()
        if include_optional:
            return V1DiagnosticClearArpDeviceIdPutRequest(
                entry = [
                    graphiant_sdk.models.diagnostic_tools_arp_entry.diagnosticToolsArpEntry(
                        address = graphiant_sdk.models.diagnostic_tools_arp_entry_address.diagnosticToolsArpEntryAddress(), 
                        all_entry = True, 
                        interface_name = 'GigabitEthernet0/2', )
                    ]
            )
        else:
            return V1DiagnosticClearArpDeviceIdPutRequest(
        )
        """

    def testV1DiagnosticClearArpDeviceIdPutRequest(self):
        """Test V1DiagnosticClearArpDeviceIdPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
