# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_forwarding_policy_config import ManaV2ForwardingPolicyConfig

class TestManaV2ForwardingPolicyConfig(unittest.TestCase):
    """ManaV2ForwardingPolicyConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2ForwardingPolicyConfig:
        """Test ManaV2ForwardingPolicyConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2ForwardingPolicyConfig`
        """
        model = ManaV2ForwardingPolicyConfig()
        if include_optional:
            return ManaV2ForwardingPolicyConfig(
                dpi_applications = {
                    'key' : graphiant_sdk.models.mana_v2_nullable_dpi_application_config.manaV2NullableDpiApplicationConfig(
                        application = graphiant_sdk.models.mana_v2_dpi_application_config.manaV2DpiApplicationConfig(
                            description = 'example string', 
                            destination_network = 'example string', 
                            destination_network_list = 'example string', 
                            destination_networks = graphiant_sdk.models.mana_v2_ip_network_list_config.manaV2IpNetworkListConfig(
                                name = 'example string', 
                                networks = [
                                    'example string'
                                    ], ), 
                            destination_port = 123, 
                            destination_port_list = 'example string', 
                            destination_ports = graphiant_sdk.models.mana_v2_l4_port_list_config.manaV2L4PortListConfig(
                                name = 'example string', 
                                ports = [
                                    123
                                    ], ), 
                            icmp_type = 123, 
                            ip_protocol = 'ENUM_VALUE', 
                            name = 'example string', 
                            source_network = 'example string', 
                            source_network_list = 'example string', 
                            source_networks = graphiant_sdk.models.mana_v2_ip_network_list_config.manaV2IpNetworkListConfig(
                                name = 'example string', ), 
                            source_port = 123, 
                            source_port_list = 'example string', 
                            source_ports = graphiant_sdk.models.mana_v2_l4_port_list_config.manaV2L4PortListConfig(
                                name = 'example string', ), ), )
                    },
                network_lists = {
                    'key' : graphiant_sdk.models.mana_v2_nullable_ip_network_list_config.manaV2NullableIpNetworkListConfig(
                        list = graphiant_sdk.models.mana_v2_ip_network_list_config.manaV2IpNetworkListConfig(
                            name = 'example string', 
                            networks = [
                                'example string'
                                ], ), )
                    },
                port_lists = {
                    'key' : graphiant_sdk.models.mana_v2_nullable_l4_port_list_config.manaV2NullableL4PortListConfig(
                        list = graphiant_sdk.models.mana_v2_l4_port_list_config.manaV2L4PortListConfig(
                            name = 'example string', 
                            ports = [
                                123
                                ], ), )
                    },
                security_rulesets = {
                    'key' : graphiant_sdk.models.mana_v2_nullable_security_policy_ruleset_config.manaV2NullableSecurityPolicyRulesetConfig(
                        ruleset = graphiant_sdk.models.mana_v2_security_policy_ruleset_config.manaV2SecurityPolicyRulesetConfig(
                            description = 'example string', 
                            global_id = 1234567891011, 
                            is_global_sync = True, 
                            name = 'example string', 
                            rules = {
                                'key' : graphiant_sdk.models.mana_v2_security_policy_ruleset_config_nullable_rule.manaV2SecurityPolicyRulesetConfigNullableRule(
                                    rule = graphiant_sdk.models.mana_v2_security_policy_ruleset_config_nullable_rule_rule.manaV2SecurityPolicyRulesetConfigNullableRuleRule(
                                        action = 'ENUM_VALUE', 
                                        description = 'example string', 
                                        downlink_burst_rate = graphiant_sdk.models.mana_v2_nullable_meter_rates.manaV2NullableMeterRates(
                                            rate = 123, ), 
                                        downlink_policer_rate = graphiant_sdk.models.mana_v2_nullable_meter_rates.manaV2NullableMeterRates(
                                            rate = 123, ), 
                                        logging = True, 
                                        match = graphiant_sdk.models.mana_v2_forwarding_policy_match_config.manaV2ForwardingPolicyMatchConfig(
                                            application = graphiant_sdk.models.mana_v2_nullable_application_match_config.manaV2NullableApplicationMatchConfig(), 
                                            content_filter = graphiant_sdk.models.mana_v2_nullable_content_filter_match_config.manaV2NullableContentFilterMatchConfig(), 
                                            destination_network = graphiant_sdk.models.mana_v2_nullable_destination_network_match_config.manaV2NullableDestinationNetworkMatchConfig(), 
                                            destination_port = 123, 
                                            destination_port_range = graphiant_sdk.models.mana_v2_port_range_config.manaV2PortRangeConfig(
                                                lower = 123, 
                                                upper = 123, ), 
                                            domain_list = graphiant_sdk.models.mana_v2_nullable_domain_list_match_config.manaV2NullableDomainListMatchConfig(), 
                                            dscp = graphiant_sdk.models.mana_v2_nullable_dscp_match_config.manaV2NullableDscpMatchConfig(), 
                                            icmp_type = 123, 
                                            ip_protocol = 'ENUM_VALUE', 
                                            protocol = graphiant_sdk.models.mana_v2_nullable_ip_protocol.manaV2NullableIpProtocol(
                                                ip_protocol = 'ENUM_VALUE', ), 
                                            source_network = graphiant_sdk.models.mana_v2_nullable_source_network_match_config.manaV2NullableSourceNetworkMatchConfig(), 
                                            source_port = 123, 
                                            source_port_range = graphiant_sdk.models.mana_v2_port_range_config.manaV2PortRangeConfig(
                                                lower = 123, 
                                                upper = 123, ), ), 
                                        name = 'example string', 
                                        seq = 123, 
                                        uplink_burst_rate = , 
                                        uplink_policer_rate = , ), )
                                }, ), )
                    },
                traffic_rulesets = {
                    'key' : graphiant_sdk.models.mana_v2_nullable_traffic_policy_ruleset_config.manaV2NullableTrafficPolicyRulesetConfig(
                        ruleset = graphiant_sdk.models.mana_v2_traffic_policy_ruleset_config.manaV2TrafficPolicyRulesetConfig(
                            description = 'example string', 
                            global_id = 1234567891011, 
                            is_global_sync = True, 
                            name = 'example string', 
                            rules = {
                                'key' : graphiant_sdk.models.mana_v2_traffic_policy_ruleset_config_nullable_rule.manaV2TrafficPolicyRulesetConfigNullableRule(
                                    rule = graphiant_sdk.models.mana_v2_traffic_policy_ruleset_config_nullable_rule_rule.manaV2TrafficPolicyRulesetConfigNullableRuleRule(
                                        action = graphiant_sdk.models.mana_v2_traffic_policy_ruleset_config_nullable_rule_rule_action.manaV2TrafficPolicyRulesetConfigNullableRuleRuleAction(
                                            backup_circuit = graphiant_sdk.models.mana_v2_nullable_set_circuit_config.manaV2NullableSetCircuitConfig(
                                                name = 'example string', ), 
                                            backup_circuit_label = graphiant_sdk.models.mana_v2_nullable_set_circuit_label_config.manaV2NullableSetCircuitLabelConfig(
                                                ipsec_label = 'ENUM_VALUE', 
                                                label = 'ENUM_VALUE', ), 
                                            egress = 'ENUM_VALUE', 
                                            logging = True, 
                                            primary_circuit = graphiant_sdk.models.mana_v2_nullable_set_circuit_config.manaV2NullableSetCircuitConfig(
                                                name = 'example string', ), 
                                            primary_circuit_label = graphiant_sdk.models.mana_v2_nullable_set_circuit_label_config.manaV2NullableSetCircuitLabelConfig(
                                                ipsec_label = 'ENUM_VALUE', 
                                                label = 'ENUM_VALUE', ), 
                                            remark = graphiant_sdk.models.mana_v2_nullable_set_dscp_config.manaV2NullableSetDscpConfig(
                                                val = graphiant_sdk.models.mana_v2_dscp.manaV2Dscp(
                                                    code_point = 123, ), ), 
                                            set_sla_class = graphiant_sdk.models.mana_v2_nullable_set_sla_class_config.manaV2NullableSetSlaClassConfig(
                                                class = 'ENUM_VALUE', ), ), 
                                        description = 'example string', 
                                        match = graphiant_sdk.models.mana_v2_forwarding_policy_match_config.manaV2ForwardingPolicyMatchConfig(
                                            application = graphiant_sdk.models.mana_v2_nullable_application_match_config.manaV2NullableApplicationMatchConfig(), 
                                            content_filter = graphiant_sdk.models.mana_v2_nullable_content_filter_match_config.manaV2NullableContentFilterMatchConfig(), 
                                            destination_network = graphiant_sdk.models.mana_v2_nullable_destination_network_match_config.manaV2NullableDestinationNetworkMatchConfig(), 
                                            destination_port = 123, 
                                            destination_port_range = graphiant_sdk.models.mana_v2_port_range_config.manaV2PortRangeConfig(
                                                lower = 123, 
                                                upper = 123, ), 
                                            domain_list = graphiant_sdk.models.mana_v2_nullable_domain_list_match_config.manaV2NullableDomainListMatchConfig(), 
                                            dscp = graphiant_sdk.models.mana_v2_nullable_dscp_match_config.manaV2NullableDscpMatchConfig(), 
                                            icmp_type = 123, 
                                            ip_protocol = 'ENUM_VALUE', 
                                            protocol = graphiant_sdk.models.mana_v2_nullable_ip_protocol.manaV2NullableIpProtocol(
                                                ip_protocol = 'ENUM_VALUE', ), 
                                            source_network = graphiant_sdk.models.mana_v2_nullable_source_network_match_config.manaV2NullableSourceNetworkMatchConfig(), 
                                            source_port = 123, 
                                            source_port_range = graphiant_sdk.models.mana_v2_port_range_config.manaV2PortRangeConfig(
                                                lower = 123, 
                                                upper = 123, ), ), 
                                        name = 'example string', 
                                        seq = 123, ), )
                                }, ), )
                    },
                zone_firewalls = {
                    'key' : graphiant_sdk.models.mana_v2_nullable_zone_firewall_config.manaV2NullableZoneFirewallConfig(
                        zone_firewall = graphiant_sdk.models.mana_v2_zone_firewall_config.manaV2ZoneFirewallConfig(
                            ip = graphiant_sdk.models.mana_v2_zone_firewall_ip_policy_config.manaV2ZoneFirewallIpPolicyConfig(
                                block_land_attacks = True, 
                                session_limit = graphiant_sdk.models.mana_v2_nullable_session_limit.manaV2NullableSessionLimit(
                                    limit = 123, ), 
                                urpf = 'ENUM_VALUE', ), 
                            udp = graphiant_sdk.models.mana_v2_zone_firewall_udp_policy_config.manaV2ZoneFirewallUdpPolicyConfig(
                                unidirectional_flow_limit = graphiant_sdk.models.mana_v2_nullable_session_limit.manaV2NullableSessionLimit(
                                    limit = 123, ), ), ), )
                    },
                zones = {
                    'key' : graphiant_sdk.models.mana_v2_nullable_security_zone_config.manaV2NullableSecurityZoneConfig(
                        zone = graphiant_sdk.models.mana_v2_security_zone_config.manaV2SecurityZoneConfig(
                            inside = 'example string', 
                            pairs = {
                                'key' : graphiant_sdk.models.mana_v2_nullable_security_zone_pair_config.manaV2NullableSecurityZonePairConfig(
                                    pair = graphiant_sdk.models.mana_v2_security_zone_pair_config.manaV2SecurityZonePairConfig(
                                        outside = 'example string', 
                                        ruleset = 'example string', 
                                        tcp_protection = True, ), )
                                }, ), )
                    }
            )
        else:
            return ManaV2ForwardingPolicyConfig(
        )
        """

    def testManaV2ForwardingPolicyConfig(self):
        """Test ManaV2ForwardingPolicyConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
