# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.sdk_automation_playbook_job import SdkAutomationPlaybookJob

class TestSdkAutomationPlaybookJob(unittest.TestCase):
    """SdkAutomationPlaybookJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SdkAutomationPlaybookJob:
        """Test SdkAutomationPlaybookJob
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SdkAutomationPlaybookJob`
        """
        model = SdkAutomationPlaybookJob()
        if include_optional:
            return SdkAutomationPlaybookJob(
                collection_version = 'example string',
                config_description = 'example string',
                config_id = 'example string',
                config_name = 'example string',
                deploy_ended_at = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, ),
                deploy_started_at = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, ),
                dry_run_ended_at = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, ),
                dry_run_started_at = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, ),
                failed_phase = 'ENUM_VALUE',
                job_id = 'example string',
                logs_available = True,
                post_deploy_check_started_at = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, ),
                run_duration_ms = 1234567891011,
                run_ended_at = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, ),
                run_number = 123,
                runner_job_id = 'example string',
                sdk_version = 'example string',
                started_by_user_id = 'example string',
                status = 'ENUM_VALUE',
                verbose_logs = True
            )
        else:
            return SdkAutomationPlaybookJob(
        )
        """

    def testSdkAutomationPlaybookJob(self):
        """Test SdkAutomationPlaybookJob"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
