# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.assurance_bucket_stats_with_id import AssuranceBucketStatsWithId

class TestAssuranceBucketStatsWithId(unittest.TestCase):
    """AssuranceBucketStatsWithId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssuranceBucketStatsWithId:
        """Test AssuranceBucketStatsWithId
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssuranceBucketStatsWithId`
        """
        model = AssuranceBucketStatsWithId()
        if include_optional:
            return AssuranceBucketStatsWithId(
                assurance_bucket = 'ENUM_VALUE',
                bucket_name_to_display = 'example string',
                prev_unique_app_count = 1234567891011,
                unique_app_count = 1234567891011
            )
        else:
            return AssuranceBucketStatsWithId(
        )
        """

    def testAssuranceBucketStatsWithId(self):
        """Test AssuranceBucketStatsWithId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
