# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_prometheus_remote_write_sink_config import ManaV2PrometheusRemoteWriteSinkConfig

class TestManaV2PrometheusRemoteWriteSinkConfig(unittest.TestCase):
    """ManaV2PrometheusRemoteWriteSinkConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2PrometheusRemoteWriteSinkConfig:
        """Test ManaV2PrometheusRemoteWriteSinkConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2PrometheusRemoteWriteSinkConfig`
        """
        model = ManaV2PrometheusRemoteWriteSinkConfig()
        if include_optional:
            return ManaV2PrometheusRemoteWriteSinkConfig(
                description = 'example string',
                host = 'example string',
                path = 'example string',
                port = 123
            )
        else:
            return ManaV2PrometheusRemoteWriteSinkConfig(
        )
        """

    def testManaV2PrometheusRemoteWriteSinkConfig(self):
        """Test ManaV2PrometheusRemoteWriteSinkConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
