# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_device_routing_odp_nbrid_get_response import V1DeviceRoutingOdpNbridGetResponse

class TestV1DeviceRoutingOdpNbridGetResponse(unittest.TestCase):
    """V1DeviceRoutingOdpNbridGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DeviceRoutingOdpNbridGetResponse:
        """Test V1DeviceRoutingOdpNbridGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DeviceRoutingOdpNbridGetResponse`
        """
        model = V1DeviceRoutingOdpNbridGetResponse()
        if include_optional:
            return V1DeviceRoutingOdpNbridGetResponse(
                nbrs = [
                    '10.121.12.34, 1211:343:ac34::12'
                    ],
                page_info = graphiant_sdk.models.common_page_info.commonPageInfo(
                    current_page = 1, 
                    end_cursor = 'xxxxxxy', 
                    has_next_page = False, 
                    has_prev_page = True, 
                    start_cursor = 'xxxxxx', 
                    total_pages = 4, 
                    total_records = 400, ),
                token = 'xxxxxxxxx'
            )
        else:
            return V1DeviceRoutingOdpNbridGetResponse(
        )
        """

    def testV1DeviceRoutingOdpNbridGetResponse(self):
        """Test V1DeviceRoutingOdpNbridGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
