# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_auth_put_request import V1AuthPutRequest

class TestV1AuthPutRequest(unittest.TestCase):
    """V1AuthPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AuthPutRequest:
        """Test V1AuthPutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AuthPutRequest`
        """
        model = V1AuthPutRequest()
        if include_optional:
            return V1AuthPutRequest(
                cert = 'example string',
                entry_point = 'example string',
                iam_type = 'ENUM_VALUE',
                issuer = 'example string'
            )
        else:
            return V1AuthPutRequest(
                cert = 'example string',
                entry_point = 'example string',
                iam_type = 'ENUM_VALUE',
                issuer = 'example string',
        )
        """

    def testV1AuthPutRequest(self):
        """Test V1AuthPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
