# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.statsmon_bandwidthtracker_bw_usage_by_region_edge_details import StatsmonBandwidthtrackerBwUsageByRegionEdgeDetails

class TestStatsmonBandwidthtrackerBwUsageByRegionEdgeDetails(unittest.TestCase):
    """StatsmonBandwidthtrackerBwUsageByRegionEdgeDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsmonBandwidthtrackerBwUsageByRegionEdgeDetails:
        """Test StatsmonBandwidthtrackerBwUsageByRegionEdgeDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsmonBandwidthtrackerBwUsageByRegionEdgeDetails`
        """
        model = StatsmonBandwidthtrackerBwUsageByRegionEdgeDetails()
        if include_optional:
            return StatsmonBandwidthtrackerBwUsageByRegionEdgeDetails(
                bwuage_sites = [
                    graphiant_sdk.models.statsmon_bandwidthtracker_bw_usage_by_site.statsmonBandwidthtrackerBwUsageBySite(
                        edge_count = 12345678910, 
                        location_id = 12345678910, 
                        location_name = 'example string', 
                        site_id = 12345678910, 
                        site_name = 'example string', 
                        usage_kbps = 123.45, )
                    ]
            )
        else:
            return StatsmonBandwidthtrackerBwUsageByRegionEdgeDetails(
        )
        """

    def testStatsmonBandwidthtrackerBwUsageByRegionEdgeDetails(self):
        """Test StatsmonBandwidthtrackerBwUsageByRegionEdgeDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
