# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_auth_login_post_response import V1AuthLoginPostResponse

class TestV1AuthLoginPostResponse(unittest.TestCase):
    """V1AuthLoginPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AuthLoginPostResponse:
        """Test V1AuthLoginPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AuthLoginPostResponse`
        """
        model = V1AuthLoginPostResponse()
        if include_optional:
            return V1AuthLoginPostResponse(
                auth = True,
                token = 'gr-auth-12345678-1234-1234-1234-123456789012-87654321-4321-4321-4321-210987654321',
                account_type = 'enterprise'
            )
        else:
            return V1AuthLoginPostResponse(
        )
        """

    def testV1AuthLoginPostResponse(self):
        """Test V1AuthLoginPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
