# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_security_zone import ManaV2SecurityZone

class TestManaV2SecurityZone(unittest.TestCase):
    """ManaV2SecurityZone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2SecurityZone:
        """Test ManaV2SecurityZone
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2SecurityZone`
        """
        model = ManaV2SecurityZone()
        if include_optional:
            return ManaV2SecurityZone(
                inside = 'example string',
                outside = 'example string',
                ruleset = 'example string',
                tcp_protection = True
            )
        else:
            return ManaV2SecurityZone(
        )
        """

    def testManaV2SecurityZone(self):
        """Test ManaV2SecurityZone"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
