# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_backbone_health_etet_sla_matrix_get_response import V1BackboneHealthEtetSlaMatrixGetResponse

class TestV1BackboneHealthEtetSlaMatrixGetResponse(unittest.TestCase):
    """V1BackboneHealthEtetSlaMatrixGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1BackboneHealthEtetSlaMatrixGetResponse:
        """Test V1BackboneHealthEtetSlaMatrixGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1BackboneHealthEtetSlaMatrixGetResponse`
        """
        model = V1BackboneHealthEtetSlaMatrixGetResponse()
        if include_optional:
            return V1BackboneHealthEtetSlaMatrixGetResponse(
                devices = [
                    graphiant_sdk.models.v1_backbone_health_etet_sla_matrix_get_response_devices_summary.v1BackboneHealthEtetSlaMatrixGetResponseDevicesSummary(
                        device_id = 1234567891011, 
                        device_name = 'example string', 
                        region = graphiant_sdk.models.statsmon_troubleshooting_region.statsmonTroubleshootingRegion(
                            region_id = 123, 
                            region_name = 'example string', ), )
                    ],
                region_status = [
                    graphiant_sdk.models.v1_backbone_health_etet_sla_matrix_get_response_region_status.v1BackboneHealthEtetSlaMatrixGetResponseRegionStatus(
                        peer_region = graphiant_sdk.models.statsmon_troubleshooting_region.statsmonTroubleshootingRegion(
                            region_id = 123, 
                            region_name = 'example string', ), 
                        region = graphiant_sdk.models.statsmon_troubleshooting_region.statsmonTroubleshootingRegion(
                            region_id = 123, 
                            region_name = 'example string', ), 
                        status = 'ENUM_VALUE', )
                    ],
                sla_matrix = [
                    graphiant_sdk.models.v1_backbone_health_etet_sla_matrix_get_response_sla_summary.v1BackboneHealthEtetSlaMatrixGetResponseSlaSummary(
                        delay_status = 'ENUM_VALUE', 
                        delay_value = 12.34, 
                        device_id = 1234567891011, 
                        device_name = 'example string', 
                        jitter_status = 'ENUM_VALUE', 
                        jitter_value = 12.34, 
                        loss_status = 'ENUM_VALUE', 
                        loss_value = 12.34, 
                        mos_value = 12.34, 
                        peer_device_id = 1234567891011, 
                        peer_device_name = 'example string', 
                        peer_region = graphiant_sdk.models.statsmon_troubleshooting_region.statsmonTroubleshootingRegion(
                            region_id = 123, 
                            region_name = 'example string', ), 
                        region = graphiant_sdk.models.statsmon_troubleshooting_region.statsmonTroubleshootingRegion(
                            region_id = 123, 
                            region_name = 'example string', ), 
                        status = 'ENUM_VALUE', )
                    ]
            )
        else:
            return V1BackboneHealthEtetSlaMatrixGetResponse(
        )
        """

    def testV1BackboneHealthEtetSlaMatrixGetResponse(self):
        """Test V1BackboneHealthEtetSlaMatrixGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
