# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_audit_logs_post_response import V2AuditLogsPostResponse

class TestV2AuditLogsPostResponse(unittest.TestCase):
    """V2AuditLogsPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2AuditLogsPostResponse:
        """Test V2AuditLogsPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2AuditLogsPostResponse`
        """
        model = V2AuditLogsPostResponse()
        if include_optional:
            return V2AuditLogsPostResponse(
                cursor_ref = 'example string',
                logs = [
                    graphiant_sdk.models.auditmon_audit_log.auditmonAuditLog(
                        action = 'example string', 
                        activity_id = 'example string', 
                        category = 'ENUM_VALUE', 
                        entity = graphiant_sdk.models.audit_activity_item.auditActivityItem(
                            id = 1234567891011, 
                            name = 'example string', 
                            type = 'ENUM_VALUE', ), 
                        job_type = 'ENUM_VALUE', 
                        target = graphiant_sdk.models.audit_activity_item.auditActivityItem(
                            id = 1234567891011, 
                            name = 'example string', 
                            type = 'ENUM_VALUE', ), 
                        ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), 
                        user = 'example string', )
                    ],
                total_logs = 12345678910
            )
        else:
            return V2AuditLogsPostResponse(
        )
        """

    def testV2AuditLogsPostResponse(self):
        """Test V2AuditLogsPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
