# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.ipfix_entity_usage import IpfixEntityUsage

class TestIpfixEntityUsage(unittest.TestCase):
    """IpfixEntityUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IpfixEntityUsage:
        """Test IpfixEntityUsage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IpfixEntityUsage`
        """
        model = IpfixEntityUsage()
        if include_optional:
            return IpfixEntityUsage(
                id = 1234567891011,
                name = 'example string',
                usage = 123.45
            )
        else:
            return IpfixEntityUsage(
        )
        """

    def testIpfixEntityUsage(self):
        """Test IpfixEntityUsage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
