# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.upgrade_gcs_release_category import UpgradeGcsReleaseCategory

class TestUpgradeGcsReleaseCategory(unittest.TestCase):
    """UpgradeGcsReleaseCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpgradeGcsReleaseCategory:
        """Test UpgradeGcsReleaseCategory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpgradeGcsReleaseCategory`
        """
        model = UpgradeGcsReleaseCategory()
        if include_optional:
            return UpgradeGcsReleaseCategory(
                content = 'example string',
                title = 'ENUM_VALUE'
            )
        else:
            return UpgradeGcsReleaseCategory(
        )
        """

    def testUpgradeGcsReleaseCategory(self):
        """Test UpgradeGcsReleaseCategory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
