# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_global_traffic_policies_device_get_request import V1GlobalTrafficPoliciesDeviceGetRequest

class TestV1GlobalTrafficPoliciesDeviceGetRequest(unittest.TestCase):
    """V1GlobalTrafficPoliciesDeviceGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GlobalTrafficPoliciesDeviceGetRequest:
        """Test V1GlobalTrafficPoliciesDeviceGetRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GlobalTrafficPoliciesDeviceGetRequest`
        """
        model = V1GlobalTrafficPoliciesDeviceGetRequest()
        if include_optional:
            return V1GlobalTrafficPoliciesDeviceGetRequest(
                device_id = 1234567891011
            )
        else:
            return V1GlobalTrafficPoliciesDeviceGetRequest(
        )
        """

    def testV1GlobalTrafficPoliciesDeviceGetRequest(self):
        """Test V1GlobalTrafficPoliciesDeviceGetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
