# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.assurance_server import AssuranceServer

class TestAssuranceServer(unittest.TestCase):
    """AssuranceServer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssuranceServer:
        """Test AssuranceServer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssuranceServer`
        """
        model = AssuranceServer()
        if include_optional:
            return AssuranceServer(
                server_ip = 'example string',
                server_port = 'example string',
                server_protocol = 'example string'
            )
        else:
            return AssuranceServer(
        )
        """

    def testAssuranceServer(self):
        """Test AssuranceServer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
