# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_site_site_id_lan_segments_post_response import V2SiteSiteIdLanSegmentsPostResponse

class TestV2SiteSiteIdLanSegmentsPostResponse(unittest.TestCase):
    """V2SiteSiteIdLanSegmentsPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2SiteSiteIdLanSegmentsPostResponse:
        """Test V2SiteSiteIdLanSegmentsPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2SiteSiteIdLanSegmentsPostResponse`
        """
        model = V2SiteSiteIdLanSegmentsPostResponse()
        if include_optional:
            return V2SiteSiteIdLanSegmentsPostResponse(
                device_segments = [
                    graphiant_sdk.models.statsmon_v2_device_segments.statsmonV2DeviceSegments(
                        device_id = 1234567891011, 
                        vrf_routes = [
                            graphiant_sdk.models.statsmon_v2_vrf_routes.statsmonV2VrfRoutes(
                                ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                                    nanos = 123, 
                                    seconds = 1234567891011, ), 
                                vrf_route = [
                                    graphiant_sdk.models.statsmon_v2_vrf_route.statsmonV2VrfRoute(
                                        ipv4_routes = 1234567891011, 
                                        ipv6_routes = 1234567891011, 
                                        total_routes = 1234567891011, 
                                        vrf_name = 'example string', )
                                    ], )
                            ], )
                    ]
            )
        else:
            return V2SiteSiteIdLanSegmentsPostResponse(
        )
        """

    def testV2SiteSiteIdLanSegmentsPostResponse(self):
        """Test V2SiteSiteIdLanSegmentsPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
