# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_portal_apikeys_post_request import V1PortalApikeysPostRequest

class TestV1PortalApikeysPostRequest(unittest.TestCase):
    """V1PortalApikeysPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1PortalApikeysPostRequest:
        """Test V1PortalApikeysPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1PortalApikeysPostRequest`
        """
        model = V1PortalApikeysPostRequest()
        if include_optional:
            return V1PortalApikeysPostRequest(
                name = 'example string'
            )
        else:
            return V1PortalApikeysPostRequest(
                name = 'example string',
        )
        """

    def testV1PortalApikeysPostRequest(self):
        """Test V1PortalApikeysPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
