# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_alarm_history_get_response import V1AlarmHistoryGetResponse

class TestV1AlarmHistoryGetResponse(unittest.TestCase):
    """V1AlarmHistoryGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AlarmHistoryGetResponse:
        """Test V1AlarmHistoryGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AlarmHistoryGetResponse`
        """
        model = V1AlarmHistoryGetResponse()
        if include_optional:
            return V1AlarmHistoryGetResponse(
                history = [
                    graphiant_sdk.models.alarms_alarm_history.alarmsAlarmHistory(
                        boot_id = '8a2ec658-f25b-11ec-b939-0242ac120002', 
                        description = 'NTP service initiated. Synchronization state is unknown.', 
                        is_cleared = False, 
                        perceived_severity = 'warning', 
                        sequence_number = 10, 
                        time = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), )
                    ]
            )
        else:
            return V1AlarmHistoryGetResponse(
        )
        """

    def testV1AlarmHistoryGetResponse(self):
        """Test V1AlarmHistoryGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
