# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_prometheus_sys_db_monitor_config import ManaV2PrometheusSysDbMonitorConfig

class TestManaV2PrometheusSysDbMonitorConfig(unittest.TestCase):
    """ManaV2PrometheusSysDbMonitorConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2PrometheusSysDbMonitorConfig:
        """Test ManaV2PrometheusSysDbMonitorConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2PrometheusSysDbMonitorConfig`
        """
        model = ManaV2PrometheusSysDbMonitorConfig()
        if include_optional:
            return ManaV2PrometheusSysDbMonitorConfig(
                interval_seconds = 123,
                name = 'example string',
                xpaths = [
                    'example string'
                    ]
            )
        else:
            return ManaV2PrometheusSysDbMonitorConfig(
        )
        """

    def testManaV2PrometheusSysDbMonitorConfig(self):
        """Test ManaV2PrometheusSysDbMonitorConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
