# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_auth_login_pre_get_response import V1AuthLoginPreGetResponse

class TestV1AuthLoginPreGetResponse(unittest.TestCase):
    """V1AuthLoginPreGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AuthLoginPreGetResponse:
        """Test V1AuthLoginPreGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AuthLoginPreGetResponse`
        """
        model = V1AuthLoginPreGetResponse()
        if include_optional:
            return V1AuthLoginPreGetResponse(
                method = 'PASSWORD',
                email = 'user@example.com',
                iam = 'Azure',
                relay_state = 'information-to-relay',
                entry_point = 'https://saml.example.com/sso'
            )
        else:
            return V1AuthLoginPreGetResponse(
                method = 'PASSWORD',
                email = 'user@example.com',
        )
        """

    def testV1AuthLoginPreGetResponse(self):
        """Test V1AuthLoginPreGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
