# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_dnsip_addresses import ManaV2DnsipAddresses

class TestManaV2DnsipAddresses(unittest.TestCase):
    """ManaV2DnsipAddresses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2DnsipAddresses:
        """Test ManaV2DnsipAddresses
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2DnsipAddresses`
        """
        model = ManaV2DnsipAddresses()
        if include_optional:
            return ManaV2DnsipAddresses(
                dynamic_servers = [
                    graphiant_sdk.models.mana_v2_dnsip_address.manaV2DnsipAddress(
                        circuit_name = 'example string', 
                        interface_name = 'example string', 
                        ipv4 = 'example string', 
                        ipv6 = 'example string', 
                        source = 'example string', 
                        stale = True, 
                        type = 'ENUM_VALUE', )
                    ]
            )
        else:
            return ManaV2DnsipAddresses(
        )
        """

    def testManaV2DnsipAddresses(self):
        """Test ManaV2DnsipAddresses"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
