# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_bwtracker_enterprise_summary_post_response import V1BwtrackerEnterpriseSummaryPostResponse

class TestV1BwtrackerEnterpriseSummaryPostResponse(unittest.TestCase):
    """V1BwtrackerEnterpriseSummaryPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1BwtrackerEnterpriseSummaryPostResponse:
        """Test V1BwtrackerEnterpriseSummaryPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1BwtrackerEnterpriseSummaryPostResponse`
        """
        model = V1BwtrackerEnterpriseSummaryPostResponse()
        if include_optional:
            return V1BwtrackerEnterpriseSummaryPostResponse(
                bwusage_summary = graphiant_sdk.models.statsmon_bandwidthtracker_bw_usage_by_enterprise_summary.statsmonBandwidthtrackerBwUsageByEnterpriseSummary(
                    bwusage_role_summary = [
                        graphiant_sdk.models.statsmon_bandwidthtracker_bw_usage_by_role_summary.statsmonBandwidthtrackerBwUsageByRoleSummary(
                            role_id = 12345678910, 
                            role_name = 'example string', 
                            usage_kbps = 123.45, )
                        ], 
                    bwusage_top_regions = [
                        graphiant_sdk.models.statsmon_bandwidthtracker_bw_usage_by_top_regions.statsmonBandwidthtrackerBwUsageByTopRegions(
                            region_id = 12345678910, 
                            region_name = 'example string', )
                        ], 
                    min_time = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                        nanos = 123, 
                        seconds = 1234567891011, ), 
                    percent_changed = 123.45, 
                    provider_count = 12345678910, 
                    region_count = 12345678910, 
                    site_count = 12345678910, 
                    usage_kbps = 123.45, )
            )
        else:
            return V1BwtrackerEnterpriseSummaryPostResponse(
        )
        """

    def testV1BwtrackerEnterpriseSummaryPostResponse(self):
        """Test V1BwtrackerEnterpriseSummaryPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
