# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_assistant_version_post_response import V2AssistantVersionPostResponse

class TestV2AssistantVersionPostResponse(unittest.TestCase):
    """V2AssistantVersionPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2AssistantVersionPostResponse:
        """Test V2AssistantVersionPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2AssistantVersionPostResponse`
        """
        model = V2AssistantVersionPostResponse()
        if include_optional:
            return V2AssistantVersionPostResponse(
                version_id = 'example string'
            )
        else:
            return V2AssistantVersionPostResponse(
        )
        """

    def testV2AssistantVersionPostResponse(self):
        """Test V2AssistantVersionPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
