# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.assurance_dns_proxy_entry import AssuranceDnsProxyEntry

class TestAssuranceDnsProxyEntry(unittest.TestCase):
    """AssuranceDnsProxyEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssuranceDnsProxyEntry:
        """Test AssuranceDnsProxyEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssuranceDnsProxyEntry`
        """
        model = AssuranceDnsProxyEntry()
        if include_optional:
            return AssuranceDnsProxyEntry(
                dnsproxy_entry_id = 'example string',
                ip_list = [
                    'example string'
                    ],
                name = 'DNSPROXY_EXCEPTION_DNS',
                name_text = 'example string',
                port_list = [
                    'example string'
                    ],
                protocol = 'example string'
            )
        else:
            return AssuranceDnsProxyEntry(
                dnsproxy_entry_id = 'example string',
                ip_list = [
                    'example string'
                    ],
                name = 'DNSPROXY_EXCEPTION_DNS',
                name_text = 'example string',
                port_list = [
                    'example string'
                    ],
                protocol = 'example string',
        )
        """

    def testAssuranceDnsProxyEntry(self):
        """Test AssuranceDnsProxyEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
