# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_snmp_vacm_view import ManaV2SnmpVacmView

class TestManaV2SnmpVacmView(unittest.TestCase):
    """ManaV2SnmpVacmView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2SnmpVacmView:
        """Test ManaV2SnmpVacmView
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2SnmpVacmView`
        """
        model = ManaV2SnmpVacmView()
        if include_optional:
            return ManaV2SnmpVacmView(
                id = 1234567891011,
                include_exclude = [
                    graphiant_sdk.models.mana_v2_snmp_vacm_view_include.manaV2SnmpVacmViewInclude(
                        id = 1234567891011, 
                        include = True, 
                        name = 'example string', )
                    ],
                name = 'example string'
            )
        else:
            return ManaV2SnmpVacmView(
        )
        """

    def testManaV2SnmpVacmView(self):
        """Test ManaV2SnmpVacmView"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
