# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2topology_device import ManaV2topologyDevice

class TestManaV2topologyDevice(unittest.TestCase):
    """ManaV2topologyDevice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2topologyDevice:
        """Test ManaV2topologyDevice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2topologyDevice`
        """
        model = ManaV2topologyDevice()
        if include_optional:
            return ManaV2topologyDevice(
                device_id = 12345678910,
                hostname = 'example string',
                location = 'example string',
                maintenance_mode = True,
                management_ip = 'example string',
                model = 'example string',
                role = 'ENUM_VALUE',
                serial_number = 'example string',
                site_id = 12345678910,
                software_version = 'example string',
                staging_mode = True,
                uptime = graphiant_sdk.models.google_protobuf_duration.googleProtobufDuration(
                    nanos = 123, 
                    seconds = 1234567891011, ),
                vrrp_interface = 'example string',
                vrrp_state = 'ENUM_VALUE'
            )
        else:
            return ManaV2topologyDevice(
        )
        """

    def testManaV2topologyDevice(self):
        """Test ManaV2topologyDevice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
