# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_devices_rma_post_request import V1DevicesRmaPostRequest

class TestV1DevicesRmaPostRequest(unittest.TestCase):
    """V1DevicesRmaPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DevicesRmaPostRequest:
        """Test V1DevicesRmaPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DevicesRmaPostRequest`
        """
        model = V1DevicesRmaPostRequest()
        if include_optional:
            return V1DevicesRmaPostRequest(
                current_device_id = 12345678910,
                new_device_id = 12345678910
            )
        else:
            return V1DevicesRmaPostRequest(
        )
        """

    def testV1DevicesRmaPostRequest(self):
        """Test V1DevicesRmaPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
