# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_interface_lagvlan_config import ManaV2InterfaceLagvlanConfig

class TestManaV2InterfaceLagvlanConfig(unittest.TestCase):
    """ManaV2InterfaceLagvlanConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2InterfaceLagvlanConfig:
        """Test ManaV2InterfaceLagvlanConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2InterfaceLagvlanConfig`
        """
        model = ManaV2InterfaceLagvlanConfig()
        if include_optional:
            return ManaV2InterfaceLagvlanConfig(
                admin_status = True,
                alias = 'example string',
                description = 'example string',
                ipv4 = graphiant_sdk.models.mana_v2_interface_ip_config.manaV2InterfaceIpConfig(
                    address = graphiant_sdk.models.mana_v2_nullable_address.manaV2NullableAddress(), 
                    dhcp = graphiant_sdk.models.mana_v2_interface_dhcp_config.manaV2InterfaceDhcpConfig(
                        dhcp_client = True, 
                        dhcp_relay = graphiant_sdk.models.mana_v2_dhcp_relay_config.manaV2DhcpRelayConfig(
                            relay_servers = [
                                'example string'
                                ], ), ), 
                    vrrp = graphiant_sdk.models.mana_v2_nullable_vrrp_group_config.manaV2NullableVrrpGroupConfig(
                        group = graphiant_sdk.models.mana_v2_vrrp_group_config.manaV2VrrpGroupConfig(
                            accept_mode = True, 
                            allow_inter_operability = True, 
                            description = 'example string', 
                            enabled = True, 
                            preempt = True, 
                            priority = 123, 
                            tracked_interfaces = [
                                graphiant_sdk.models.mana_v2_nullable_interface_priority_decrement.manaV2NullableInterfacePriorityDecrement(
                                    interface = 'example string', 
                                    priority_decrement = 123, )
                                ], 
                            virtual_ip = 'example string', 
                            virtual_router_id = 123, ), ), ),
                ipv6 = graphiant_sdk.models.mana_v2_interface_ip_config.manaV2InterfaceIpConfig(
                    address = graphiant_sdk.models.mana_v2_nullable_address.manaV2NullableAddress(), 
                    dhcp = graphiant_sdk.models.mana_v2_interface_dhcp_config.manaV2InterfaceDhcpConfig(
                        dhcp_client = True, 
                        dhcp_relay = graphiant_sdk.models.mana_v2_dhcp_relay_config.manaV2DhcpRelayConfig(
                            relay_servers = [
                                'example string'
                                ], ), ), 
                    vrrp = graphiant_sdk.models.mana_v2_nullable_vrrp_group_config.manaV2NullableVrrpGroupConfig(
                        group = graphiant_sdk.models.mana_v2_vrrp_group_config.manaV2VrrpGroupConfig(
                            accept_mode = True, 
                            allow_inter_operability = True, 
                            description = 'example string', 
                            enabled = True, 
                            preempt = True, 
                            priority = 123, 
                            tracked_interfaces = [
                                graphiant_sdk.models.mana_v2_nullable_interface_priority_decrement.manaV2NullableInterfacePriorityDecrement(
                                    interface = 'example string', 
                                    priority_decrement = 123, )
                                ], 
                            virtual_ip = 'example string', 
                            virtual_router_id = 123, ), ), ),
                segment = 'example string',
                vlan = 123
            )
        else:
            return ManaV2InterfaceLagvlanConfig(
        )
        """

    def testManaV2InterfaceLagvlanConfig(self):
        """Test ManaV2InterfaceLagvlanConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
