# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.alertservice_update_integration_body import AlertserviceUpdateIntegrationBody

class TestAlertserviceUpdateIntegrationBody(unittest.TestCase):
    """AlertserviceUpdateIntegrationBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlertserviceUpdateIntegrationBody:
        """Test AlertserviceUpdateIntegrationBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlertserviceUpdateIntegrationBody`
        """
        model = AlertserviceUpdateIntegrationBody()
        if include_optional:
            return AlertserviceUpdateIntegrationBody(
                details = graphiant_sdk.models.alertservice_integration_details.alertserviceIntegrationDetails(
                    opsgenie_key = 'example string', 
                    opsramp_details = 'example string', 
                    webhook_url = 'example string', ),
                enterprise = 1234567891011,
                integration_type = 'ENUM_VALUE',
                is_active = True,
                nick_name = 'example string',
                updated_by = 'example string'
            )
        else:
            return AlertserviceUpdateIntegrationBody(
                enterprise = 1234567891011,
                integration_type = 'ENUM_VALUE',
                nick_name = 'example string',
        )
        """

    def testAlertserviceUpdateIntegrationBody(self):
        """Test AlertserviceUpdateIntegrationBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
