# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranets_id_put_request import V1ExtranetsIdPutRequest

class TestV1ExtranetsIdPutRequest(unittest.TestCase):
    """V1ExtranetsIdPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetsIdPutRequest:
        """Test V1ExtranetsIdPutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetsIdPutRequest`
        """
        model = V1ExtranetsIdPutRequest()
        if include_optional:
            return V1ExtranetsIdPutRequest(
                policy = graphiant_sdk.models.mana_v2_extranet_policy_input.manaV2ExtranetPolicyInput(
                    auto = graphiant_sdk.models.mana_v2_extranet_auto_reverse_routes.manaV2ExtranetAutoReverseRoutes(
                        auto_propagate = True, 
                        excluded_prefixes = [
                            'example string'
                            ], ), 
                    branches = graphiant_sdk.models.mana_v2_policy_target_input.manaV2PolicyTargetInput(
                        excluded_devices = [
                            1234567891011
                            ], 
                        prefix_set = graphiant_sdk.models.mana_v2_enterprise_prefix_set_input.manaV2EnterprisePrefixSetInput(
                            description = 'example string', 
                            entries = {
                                'key' : graphiant_sdk.models.mana_v2_enterprise_prefix_set_input_entry.manaV2EnterprisePrefixSetInputEntry(
                                    ip_prefix = 'example string', 
                                    mask_lower = 123, 
                                    mask_upper = 123, 
                                    seq = 123, )
                                }, 
                            id = 1234567891011, 
                            mode = 'ENUM_VALUE', 
                            name = 'example string', ), 
                        sites = [
                            1234567891011
                            ], ), 
                    description = 'example string', 
                    host_prefix_set = graphiant_sdk.models.mana_v2_enterprise_prefix_set_input.manaV2EnterprisePrefixSetInput(
                        description = 'example string', 
                        id = 1234567891011, 
                        mode = 'ENUM_VALUE', 
                        name = 'example string', ), 
                    manual = graphiant_sdk.models.mana_v2_extranet_manual_reverse_routes.manaV2ExtranetManualReverseRoutes(
                        prefixes = [
                            'example string'
                            ], ), 
                    name = 'example string', 
                    shared_prefixes = [
                        'example string'
                        ], 
                    shared_segment = 1234567891011, 
                    source = graphiant_sdk.models.mana_v2_policy_target_input.manaV2PolicyTargetInput(), 
                    target_segments = [
                        1234567891011
                        ], 
                    type = 'ENUM_VALUE', )
            )
        else:
            return V1ExtranetsIdPutRequest(
        )
        """

    def testV1ExtranetsIdPutRequest(self):
        """Test V1ExtranetsIdPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
