# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_devices_inventory_post_response_data import V1DevicesInventoryPostResponseData

class TestV1DevicesInventoryPostResponseData(unittest.TestCase):
    """V1DevicesInventoryPostResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DevicesInventoryPostResponseData:
        """Test V1DevicesInventoryPostResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DevicesInventoryPostResponseData`
        """
        model = V1DevicesInventoryPostResponseData()
        if include_optional:
            return V1DevicesInventoryPostResponseData(
                device_serial = 'example string',
                uuid = 'example string'
            )
        else:
            return V1DevicesInventoryPostResponseData(
        )
        """

    def testV1DevicesInventoryPostResponseData(self):
        """Test V1DevicesInventoryPostResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
