# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_device_routing_ospfv2_area_lsdb_get_response import V1DeviceRoutingOspfv2AreaLsdbGetResponse

class TestV1DeviceRoutingOspfv2AreaLsdbGetResponse(unittest.TestCase):
    """V1DeviceRoutingOspfv2AreaLsdbGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DeviceRoutingOspfv2AreaLsdbGetResponse:
        """Test V1DeviceRoutingOspfv2AreaLsdbGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DeviceRoutingOspfv2AreaLsdbGetResponse`
        """
        model = V1DeviceRoutingOspfv2AreaLsdbGetResponse()
        if include_optional:
            return V1DeviceRoutingOspfv2AreaLsdbGetResponse(
                lsas = [
                    graphiant_sdk.models.routing_ospflsa.routingOspflsa(
                        advertising_router = '172.121.12.34', 
                        age = 3242342, 
                        asexternal_lsa = graphiant_sdk.models.routing_ospfas_external_lsa.routingOspfasExternalLsa(
                            forwarding_address = 'example string', 
                            metric = 123, 
                            metric_type = 'example string', 
                            network_mask = 123, 
                            tag = 123, 
                            tos_metric = graphiant_sdk.models.routing_ospflsa_tos_metric.routingOspflsaTosMetric(
                                tos = 123, ), ), 
                        checksum = 2343232, 
                        length = 123132, 
                        link_id = '143.12.1.5', 
                        network_lsa = graphiant_sdk.models.routing_ospf_network_lsa.routingOspfNetworkLsa(
                            attached_routers = [
                                'example string'
                                ], 
                            network_mask = 123, ), 
                        router_lsa = graphiant_sdk.models.routing_ospf_router_lsa.routingOspfRouterLsa(
                            links = [
                                graphiant_sdk.models.routing_ospf_router_lsa_link.routingOspfRouterLsaLink(
                                    link_data = 'example string', 
                                    link_id = 'example string', 
                                    link_type = 'example string', 
                                    metric = 123, )
                                ], ), 
                        sequence_number = '0x80000001', 
                        summary_lsa = graphiant_sdk.models.routing_ospf_summary_lsa.routingOspfSummaryLsa(
                            network_mask = 123, ), 
                        type = 'Router', )
                    ],
                page_info = graphiant_sdk.models.common_page_info.commonPageInfo(
                    current_page = 1, 
                    end_cursor = 'xxxxxxy', 
                    has_next_page = False, 
                    has_prev_page = True, 
                    start_cursor = 'xxxxxx', 
                    total_pages = 4, 
                    total_records = 400, ),
                token = 'xxxxxxxxx'
            )
        else:
            return V1DeviceRoutingOspfv2AreaLsdbGetResponse(
        )
        """

    def testV1DeviceRoutingOspfv2AreaLsdbGetResponse(self):
        """Test V1DeviceRoutingOspfv2AreaLsdbGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
