# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_backbone_health_top_devices_by_alerts_post_response_device_counts import V1BackboneHealthTopDevicesByAlertsPostResponseDeviceCounts

class TestV1BackboneHealthTopDevicesByAlertsPostResponseDeviceCounts(unittest.TestCase):
    """V1BackboneHealthTopDevicesByAlertsPostResponseDeviceCounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1BackboneHealthTopDevicesByAlertsPostResponseDeviceCounts:
        """Test V1BackboneHealthTopDevicesByAlertsPostResponseDeviceCounts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1BackboneHealthTopDevicesByAlertsPostResponseDeviceCounts`
        """
        model = V1BackboneHealthTopDevicesByAlertsPostResponseDeviceCounts()
        if include_optional:
            return V1BackboneHealthTopDevicesByAlertsPostResponseDeviceCounts(
                device_counts = [
                    graphiant_sdk.models.v1_backbone_health_top_devices_by_alerts_post_response_device_counts_device_count.v1BackboneHealthTopDevicesByAlertsPostResponseDeviceCountsDeviceCount(
                        device_name = 'example string', 
                        num_alerts = 123, )
                    ]
            )
        else:
            return V1BackboneHealthTopDevicesByAlertsPostResponseDeviceCounts(
        )
        """

    def testV1BackboneHealthTopDevicesByAlertsPostResponseDeviceCounts(self):
        """Test V1BackboneHealthTopDevicesByAlertsPostResponseDeviceCounts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
