# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.statsmon_troubleshooting_system_stat import StatsmonTroubleshootingSystemStat

class TestStatsmonTroubleshootingSystemStat(unittest.TestCase):
    """StatsmonTroubleshootingSystemStat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsmonTroubleshootingSystemStat:
        """Test StatsmonTroubleshootingSystemStat
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsmonTroubleshootingSystemStat`
        """
        model = StatsmonTroubleshootingSystemStat()
        if include_optional:
            return StatsmonTroubleshootingSystemStat(
                interface_name = 'example string',
                peer_name = 'example string',
                time = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, ),
                value = 123.45
            )
        else:
            return StatsmonTroubleshootingSystemStat(
        )
        """

    def testStatsmonTroubleshootingSystemStat(self):
        """Test StatsmonTroubleshootingSystemStat"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
