# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_event_enterprise_get_response import V1EventEnterpriseGetResponse

class TestV1EventEnterpriseGetResponse(unittest.TestCase):
    """V1EventEnterpriseGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1EventEnterpriseGetResponse:
        """Test V1EventEnterpriseGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1EventEnterpriseGetResponse`
        """
        model = V1EventEnterpriseGetResponse()
        if include_optional:
            return V1EventEnterpriseGetResponse(
                events = [
                    graphiant_sdk.models.event_event.eventEvent(
                        actions = [
                            'UIUpdate'
                            ], 
                        device_id = 30000000001, 
                        enterprise_id = 30000000001, 
                        event_data = 'InterfaceOperStateChange', 
                        event_id = 30000000001, 
                        event_time = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), 
                        hostname = 'example string', 
                        severity = 'major', 
                        type = 'InterfaceOperStateChange', )
                    ]
            )
        else:
            return V1EventEnterpriseGetResponse(
        )
        """

    def testV1EventEnterpriseGetResponse(self):
        """Test V1EventEnterpriseGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
