# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_nullable_snmp_vacm_group_member_value import ManaV2NullableSnmpVacmGroupMemberValue

class TestManaV2NullableSnmpVacmGroupMemberValue(unittest.TestCase):
    """ManaV2NullableSnmpVacmGroupMemberValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2NullableSnmpVacmGroupMemberValue:
        """Test ManaV2NullableSnmpVacmGroupMemberValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2NullableSnmpVacmGroupMemberValue`
        """
        model = ManaV2NullableSnmpVacmGroupMemberValue()
        if include_optional:
            return ManaV2NullableSnmpVacmGroupMemberValue(
                member = graphiant_sdk.models.mana_v2_snmp_vacm_group_member_config.manaV2SnmpVacmGroupMemberConfig(
                    community = 'example string', 
                    security_model = 'ENUM_VALUE', 
                    security_name = 'example string', 
                    type = 'ENUM_VALUE', )
            )
        else:
            return ManaV2NullableSnmpVacmGroupMemberValue(
        )
        """

    def testManaV2NullableSnmpVacmGroupMemberValue(self):
        """Test ManaV2NullableSnmpVacmGroupMemberValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
