# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_device_snapshot_post_request import V1DeviceSnapshotPostRequest

class TestV1DeviceSnapshotPostRequest(unittest.TestCase):
    """V1DeviceSnapshotPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DeviceSnapshotPostRequest:
        """Test V1DeviceSnapshotPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DeviceSnapshotPostRequest`
        """
        model = V1DeviceSnapshotPostRequest()
        if include_optional:
            return V1DeviceSnapshotPostRequest(
                category = 'ENUM_VALUE',
                device_id = 1234567891011,
                golden = True,
                name = 'example string'
            )
        else:
            return V1DeviceSnapshotPostRequest(
        )
        """

    def testV1DeviceSnapshotPostRequest(self):
        """Test V1DeviceSnapshotPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
