# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_backbone_health_device_device_id_post_response import V1BackboneHealthDeviceDeviceIdPostResponse

class TestV1BackboneHealthDeviceDeviceIdPostResponse(unittest.TestCase):
    """V1BackboneHealthDeviceDeviceIdPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1BackboneHealthDeviceDeviceIdPostResponse:
        """Test V1BackboneHealthDeviceDeviceIdPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1BackboneHealthDeviceDeviceIdPostResponse`
        """
        model = V1BackboneHealthDeviceDeviceIdPostResponse()
        if include_optional:
            return V1BackboneHealthDeviceDeviceIdPostResponse(
                control_plane = graphiant_sdk.models.statsmon_backbonehealth_control_plane.statsmonBackbonehealthControlPlane(
                    control_transitions = graphiant_sdk.models.statsmon_backbonehealth_transition_series.statsmonBackbonehealthTransitionSeries(
                        transitions = [
                            graphiant_sdk.models.statsmon_backbonehealth_transitions.statsmonBackbonehealthTransitions(
                                name = 'example string', )
                            ], ), 
                    management_transitions = graphiant_sdk.models.statsmon_backbonehealth_transition_series.statsmonBackbonehealthTransitionSeries(), 
                    status = 'ENUM_VALUE', ),
                data_plane = graphiant_sdk.models.statsmon_backbonehealth_data_plane.statsmonBackbonehealthDataPlane(
                    down_transitions = [
                        graphiant_sdk.models.statsmon_backbonehealth_transitions.statsmonBackbonehealthTransitions(
                            name = 'example string', 
                            transitions = [
                                graphiant_sdk.models.statsmon_troubleshooting_system_stat.statsmonTroubleshootingSystemStat(
                                    interface_name = 'example string', 
                                    peer_name = 'example string', 
                                    time = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                                        nanos = 123, 
                                        seconds = 1234567891011, ), 
                                    value = 123.45, )
                                ], )
                        ], 
                    session_slas = [
                        graphiant_sdk.models.statsmon_troubleshooting_session_sla.statsmonTroubleshootingSessionSla(
                            name = 'example string', 
                            values = [
                                graphiant_sdk.models.statsmon_troubleshooting_sla_value.statsmonTroubleshootingSlaValue(
                                    delay_value = 123.45, 
                                    jitter_value = 123.45, 
                                    loss_value = 123.45, 
                                    status = 'ENUM_VALUE', 
                                    value = 123.45, )
                                ], )
                        ], 
                    status = 'ENUM_VALUE', ),
                issues = [
                    graphiant_sdk.models.statsmon_troubleshooting_issue.statsmonTroubleshootingIssue(
                        alert_id = 'example string', 
                        allow_listed = True, 
                        component = 'example string', 
                        end_time = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), 
                        entity = 'example string', 
                        issue = 'example string', 
                        mute_listed = True, 
                        notification_created = True, 
                        plane = 'example string', 
                        reason = 'example string', 
                        severity = 'ENUM_VALUE', 
                        start_time = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), 
                        status = 'ENUM_VALUE', )
                    ],
                qoe_matrix = graphiant_sdk.models.statsmon_backbonehealth_get_qoe_matrix_response.statsmonBackbonehealthGetQoeMatrixResponse(
                    devices = [
                        graphiant_sdk.models.statsmon_backbonehealth_get_qoe_matrix_response_devices_summary.statsmonBackbonehealthGetQOEMatrixResponseDevicesSummary(
                            device_id = 1234567891011, 
                            device_name = 'example string', 
                            region = graphiant_sdk.models.statsmon_troubleshooting_region.statsmonTroubleshootingRegion(
                                region_id = 123, 
                                region_name = 'example string', ), )
                        ], 
                    qoe_matrix = [
                        graphiant_sdk.models.statsmon_backbonehealth_get_qoe_matrix_response_qoe_session_summary.statsmonBackbonehealthGetQOEMatrixResponseQoeSessionSummary(
                            box = [
                                graphiant_sdk.models.statsmon_backbonehealth_get_qoe_matrix_response_qoe_session_summary_qoe_session_box.statsmonBackbonehealthGetQOEMatrixResponseQoeSessionSummaryQoeSessionBox(
                                    delay_value = 123.45, 
                                    end_time = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                                        nanos = 123, 
                                        seconds = 1234567891011, ), 
                                    jitter_value = 123.45, 
                                    loss_value = 123.45, 
                                    start_time = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                                        nanos = 123, 
                                        seconds = 1234567891011, ), 
                                    status = 'ENUM_VALUE', 
                                    value = 123.45, )
                                ], 
                            device_id = 1234567891011, 
                            device_region = graphiant_sdk.models.statsmon_troubleshooting_region.statsmonTroubleshootingRegion(
                                region_id = 123, 
                                region_name = 'example string', ), 
                            peer_device_id = 1234567891011, 
                            peer_device_region = , 
                            session_name = 'example string', )
                        ], ),
                role = 'ENUM_VALUE',
                status = 'ENUM_VALUE',
                sw_version = 'example string',
                sw_version_v2 = graphiant_sdk.models.upgrade_sw_version.upgradeSwVersion(
                    name = 'example string', 
                    release = 'ENUM_VALUE', 
                    version = 'example string', ),
                system_plane = graphiant_sdk.models.statsmon_backbonehealth_system_plane.statsmonBackbonehealthSystemPlane(
                    cpu = [
                        graphiant_sdk.models.statsmon_troubleshooting_system_stat.statsmonTroubleshootingSystemStat(
                            interface_name = 'example string', 
                            peer_name = 'example string', 
                            time = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                                nanos = 123, 
                                seconds = 1234567891011, ), 
                            value = 123.45, )
                        ], 
                    crashes = [
                        graphiant_sdk.models.statsmon_troubleshooting_crash.statsmonTroubleshootingCrash()
                        ], 
                    disk = [
                        graphiant_sdk.models.statsmon_troubleshooting_system_stat.statsmonTroubleshootingSystemStat(
                            interface_name = 'example string', 
                            peer_name = 'example string', 
                            value = 123.45, )
                        ], 
                    last_crash = graphiant_sdk.models.statsmon_troubleshooting_last_crash.statsmonTroubleshootingLastCrash(
                        crash_details = 'example string', 
                        reason = 'example string', 
                        up_since_ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), ), 
                    maintenance_windows = [
                        graphiant_sdk.models.statsmon_troubleshooting_maintenance_window.statsmonTroubleshootingMaintenanceWindow(
                            time_window = graphiant_sdk.models.statsmon_troubleshooting_time_window.statsmonTroubleshootingTimeWindow(
                                bucket_size_sec = 123, 
                                old_ts = , 
                                recent_ts = , ), )
                        ], 
                    memory = [
                        
                        ], 
                    overheating = [
                        graphiant_sdk.models.statsmon_troubleshooting_overheating.statsmonTroubleshootingOverheating()
                        ], 
                    status = 'ENUM_VALUE', 
                    temperature_series = [
                        
                        ], ),
                up_since_ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, )
            )
        else:
            return V1BackboneHealthDeviceDeviceIdPostResponse(
        )
        """

    def testV1BackboneHealthDeviceDeviceIdPostResponse(self):
        """Test V1BackboneHealthDeviceDeviceIdPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
