# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_troubleshooting_top_sites_by_alerts_post_response_site_counts import V1TroubleshootingTopSitesByAlertsPostResponseSiteCounts

class TestV1TroubleshootingTopSitesByAlertsPostResponseSiteCounts(unittest.TestCase):
    """V1TroubleshootingTopSitesByAlertsPostResponseSiteCounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1TroubleshootingTopSitesByAlertsPostResponseSiteCounts:
        """Test V1TroubleshootingTopSitesByAlertsPostResponseSiteCounts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1TroubleshootingTopSitesByAlertsPostResponseSiteCounts`
        """
        model = V1TroubleshootingTopSitesByAlertsPostResponseSiteCounts()
        if include_optional:
            return V1TroubleshootingTopSitesByAlertsPostResponseSiteCounts(
                site_counts = [
                    graphiant_sdk.models.v1_troubleshooting_top_sites_by_alerts_post_response_site_counts_site_count.v1TroubleshootingTopSitesByAlertsPostResponseSiteCountsSiteCount(
                        num_alerts = 123, 
                        site_name = 'example string', )
                    ]
            )
        else:
            return V1TroubleshootingTopSitesByAlertsPostResponseSiteCounts(
        )
        """

    def testV1TroubleshootingTopSitesByAlertsPostResponseSiteCounts(self):
        """Test V1TroubleshootingTopSitesByAlertsPostResponseSiteCounts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
