# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_ipsec_routing_config import ManaV2IpsecRoutingConfig

class TestManaV2IpsecRoutingConfig(unittest.TestCase):
    """ManaV2IpsecRoutingConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2IpsecRoutingConfig:
        """Test ManaV2IpsecRoutingConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2IpsecRoutingConfig`
        """
        model = ManaV2IpsecRoutingConfig()
        if include_optional:
            return ManaV2IpsecRoutingConfig(
                bgp = graphiant_sdk.models.mana_v2_i_psec_bgp_route_config.manaV2IPsecBgpRouteConfig(
                    address_families = {
                        'key' : graphiant_sdk.models.mana_v2_nullable_bgp_neighbor_address_family_config.manaV2NullableBgpNeighborAddressFamilyConfig(
                            family = graphiant_sdk.models.mana_v2_bgp_neighbor_address_family_config.manaV2BgpNeighborAddressFamilyConfig(
                                address_family = 'ENUM_VALUE', 
                                inbound_policy = graphiant_sdk.models.mana_v2_nullable_policy_name.manaV2NullablePolicyName(
                                    policy = 'example string', ), 
                                outbound_policy = graphiant_sdk.models.mana_v2_nullable_policy_name.manaV2NullablePolicyName(
                                    policy = 'example string', ), ), )
                        }, 
                    hold_timer = 123, 
                    keepalive_timer = 123, 
                    md5_password = graphiant_sdk.models.mana_v2_nullable_md5_password.manaV2NullableMd5Password(), 
                    peer_asn = 123, 
                    send_community = True, ),
                static = graphiant_sdk.models.mana_v2_i_psec_static_route_config.manaV2IPsecStaticRouteConfig(
                    destination_prefix = [
                        'example string'
                        ], )
            )
        else:
            return ManaV2IpsecRoutingConfig(
        )
        """

    def testManaV2IpsecRoutingConfig(self):
        """Test ManaV2IpsecRoutingConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
