# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_apps_app_summary_post_response import V1AppsAppSummaryPostResponse

class TestV1AppsAppSummaryPostResponse(unittest.TestCase):
    """V1AppsAppSummaryPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AppsAppSummaryPostResponse:
        """Test V1AppsAppSummaryPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AppsAppSummaryPostResponse`
        """
        model = V1AppsAppSummaryPostResponse()
        if include_optional:
            return V1AppsAppSummaryPostResponse(
                app_summary = graphiant_sdk.models.ipfix_app_state_summary_count.ipfixAppStateSummaryCount(
                    app_health = {
                        'key' : 123
                        }, 
                    app_incidents = graphiant_sdk.models.ipfix_app_incidents.ipfixAppIncidents(
                        data = [
                            graphiant_sdk.models.ipfix_app_incidents_data.ipfixAppIncidentsData(
                                app_count = 123, 
                                app_status = 'ENUM_VALUE', 
                                ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                                    nanos = 123, 
                                    seconds = 1234567891011, ), )
                            ], ), 
                    apps_on_device_count = 123, 
                    average_qoe = 123.45, 
                    circuits_incidents = [
                        graphiant_sdk.models.statsmon_circuits_incidents.statsmonCircuitsIncidents(
                            name = 'example string', )
                        ], 
                    circuits_incidentsv2 = [
                        graphiant_sdk.models.statsmon_v2_circuit_incidents.statsmonV2CircuitIncidents()
                        ], )
            )
        else:
            return V1AppsAppSummaryPostResponse(
        )
        """

    def testV1AppsAppSummaryPostResponse(self):
        """Test V1AppsAppSummaryPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
