# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranets_monitoring_traffic_security_policy_post_response import V1ExtranetsMonitoringTrafficSecurityPolicyPostResponse

class TestV1ExtranetsMonitoringTrafficSecurityPolicyPostResponse(unittest.TestCase):
    """V1ExtranetsMonitoringTrafficSecurityPolicyPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetsMonitoringTrafficSecurityPolicyPostResponse:
        """Test V1ExtranetsMonitoringTrafficSecurityPolicyPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetsMonitoringTrafficSecurityPolicyPostResponse`
        """
        model = V1ExtranetsMonitoringTrafficSecurityPolicyPostResponse()
        if include_optional:
            return V1ExtranetsMonitoringTrafficSecurityPolicyPostResponse(
                security_rules = [
                    graphiant_sdk.models.mana_v2_security_policy_rule_row.manaV2SecurityPolicyRuleRow(
                        device = graphiant_sdk.models.mana_v2_site_device_stub.manaV2SiteDeviceStub(
                            hostname = 'example string', 
                            id = 1234567891011, ), 
                        security_policy_rule = graphiant_sdk.models.mana_v2_security_policy_rule.manaV2SecurityPolicyRule(
                            action = 'ENUM_VALUE', 
                            implicit = True, 
                            match = graphiant_sdk.models.mana_v2_policy_match.manaV2PolicyMatch(
                                destination_port = 123, 
                                destination_prefix = 'example string', 
                                icmp_type = 123, 
                                protocol = 123, 
                                source_port = 123, 
                                source_prefix = 'example string', ), 
                            policy_rule_index = 1234567891011, 
                            seq = 123, ), 
                        vrf_name = 'example string', )
                    ],
                traffic_rules = [
                    graphiant_sdk.models.mana_v2_traffic_policy_rule_row.manaV2TrafficPolicyRuleRow(
                        device = graphiant_sdk.models.mana_v2_site_device_stub.manaV2SiteDeviceStub(
                            hostname = 'example string', 
                            id = 1234567891011, ), 
                        traffic_policy_rule = graphiant_sdk.models.mana_v2_traffic_policy_rule.manaV2TrafficPolicyRule(
                            action = graphiant_sdk.models.mana_v2_traffic_policy_action.manaV2TrafficPolicyAction(
                                backup = 'ENUM_VALUE', 
                                class = 'ENUM_VALUE', 
                                primary = 'ENUM_VALUE', 
                                result = 'ENUM_VALUE', ), 
                            match = graphiant_sdk.models.mana_v2_policy_match.manaV2PolicyMatch(
                                destination_port = 123, 
                                destination_prefix = 'example string', 
                                icmp_type = 123, 
                                protocol = 123, 
                                source_port = 123, 
                                source_prefix = 'example string', ), 
                            policy_rule_index = 1234567891011, 
                            seq = 123, ), 
                        vrf_name = 'example string', )
                    ]
            )
        else:
            return V1ExtranetsMonitoringTrafficSecurityPolicyPostResponse(
        )
        """

    def testV1ExtranetsMonitoringTrafficSecurityPolicyPostResponse(self):
        """Test V1ExtranetsMonitoringTrafficSecurityPolicyPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
