# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_global_apps_custom_get_response import V1GlobalAppsCustomGetResponse

class TestV1GlobalAppsCustomGetResponse(unittest.TestCase):
    """V1GlobalAppsCustomGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GlobalAppsCustomGetResponse:
        """Test V1GlobalAppsCustomGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GlobalAppsCustomGetResponse`
        """
        model = V1GlobalAppsCustomGetResponse()
        if include_optional:
            return V1GlobalAppsCustomGetResponse(
                entries = [
                    graphiant_sdk.models.v1_global_apps_custom_get_response_entry.v1GlobalAppsCustomGetResponseEntry(
                        app = graphiant_sdk.models.mana_v2_app.manaV2App(
                            description = 'example string', 
                            identifier = graphiant_sdk.models.mana_v2_app_identifier.manaV2AppIdentifier(
                                id = 1234567891011, 
                                type = 'ENUM_VALUE', ), 
                            name = 'example string', ), 
                        app_config = graphiant_sdk.models.mana_v2_global_app_config.manaV2GlobalAppConfig(
                            description = 'example string', 
                            ip_lists = [
                                'example string'
                                ], 
                            ip_prefixes = [
                                'example string'
                                ], 
                            ip_protocol = 'ENUM_VALUE', 
                            name = 'example string', 
                            port_ranges = [
                                graphiant_sdk.models.mana_v2_global_app_port_range.manaV2GlobalAppPortRange(
                                    lower = 123, 
                                    upper = 123, )
                                ], 
                            url = 'example string', ), 
                        app_list_reference_count = 123, 
                        policy_reference_count = 123, )
                    ]
            )
        else:
            return V1GlobalAppsCustomGetResponse(
        )
        """

    def testV1GlobalAppsCustomGetResponse(self):
        """Test V1GlobalAppsCustomGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
