# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_extranets_b2b_peering_match_service_to_customer_post_response import V1ExtranetsB2bPeeringMatchServiceToCustomerPostResponse

class TestV1ExtranetsB2bPeeringMatchServiceToCustomerPostResponse(unittest.TestCase):
    """V1ExtranetsB2bPeeringMatchServiceToCustomerPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExtranetsB2bPeeringMatchServiceToCustomerPostResponse:
        """Test V1ExtranetsB2bPeeringMatchServiceToCustomerPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExtranetsB2bPeeringMatchServiceToCustomerPostResponse`
        """
        model = V1ExtranetsB2bPeeringMatchServiceToCustomerPostResponse()
        if include_optional:
            return V1ExtranetsB2bPeeringMatchServiceToCustomerPostResponse(
                match_id = 1234567891011,
                service = [
                    graphiant_sdk.models.mana_v2_b2b_extranet_match_service_to_customer.manaV2B2bExtranetMatchServiceToCustomer(
                        id = 1234567891011, 
                        lan_segment = 1234567891011, 
                        nat = [
                            graphiant_sdk.models.mana_v2_b2b_nat.manaV2B2bNat(
                                outside_nat_prefix = 'example string', 
                                prefix = 'example string', )
                            ], 
                        num_customers = 123, 
                        service_prefixes = [
                            graphiant_sdk.models.mana_v2_b2b_extranet_prefix_tag.manaV2B2bExtranetPrefixTag(
                                prefix = 'example string', 
                                tag = 'example string', )
                            ], )
                    ]
            )
        else:
            return V1ExtranetsB2bPeeringMatchServiceToCustomerPostResponse(
        )
        """

    def testV1ExtranetsB2bPeeringMatchServiceToCustomerPostResponse(self):
        """Test V1ExtranetsB2bPeeringMatchServiceToCustomerPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
