# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.statsmon_backbonehealth_transition_series import StatsmonBackbonehealthTransitionSeries

class TestStatsmonBackbonehealthTransitionSeries(unittest.TestCase):
    """StatsmonBackbonehealthTransitionSeries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsmonBackbonehealthTransitionSeries:
        """Test StatsmonBackbonehealthTransitionSeries
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsmonBackbonehealthTransitionSeries`
        """
        model = StatsmonBackbonehealthTransitionSeries()
        if include_optional:
            return StatsmonBackbonehealthTransitionSeries(
                transitions = [
                    graphiant_sdk.models.statsmon_backbonehealth_transitions.statsmonBackbonehealthTransitions(
                        name = 'example string', )
                    ]
            )
        else:
            return StatsmonBackbonehealthTransitionSeries(
        )
        """

    def testStatsmonBackbonehealthTransitionSeries(self):
        """Test StatsmonBackbonehealthTransitionSeries"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
