# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_auth_login_post_request import V1AuthLoginPostRequest

class TestV1AuthLoginPostRequest(unittest.TestCase):
    """V1AuthLoginPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AuthLoginPostRequest:
        """Test V1AuthLoginPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AuthLoginPostRequest`
        """
        model = V1AuthLoginPostRequest()
        if include_optional:
            return V1AuthLoginPostRequest(
                username = 'user@example.com',
                password = 'password123'
            )
        else:
            return V1AuthLoginPostRequest(
                username = 'user@example.com',
                password = 'password123',
        )
        """

    def testV1AuthLoginPostRequest(self):
        """Test V1AuthLoginPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
