# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_global_apps_categories_category_id_apps_get_response import V1GlobalAppsCategoriesCategoryIdAppsGetResponse

class TestV1GlobalAppsCategoriesCategoryIdAppsGetResponse(unittest.TestCase):
    """V1GlobalAppsCategoriesCategoryIdAppsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GlobalAppsCategoriesCategoryIdAppsGetResponse:
        """Test V1GlobalAppsCategoriesCategoryIdAppsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GlobalAppsCategoriesCategoryIdAppsGetResponse`
        """
        model = V1GlobalAppsCategoriesCategoryIdAppsGetResponse()
        if include_optional:
            return V1GlobalAppsCategoriesCategoryIdAppsGetResponse(
                apps = [
                    graphiant_sdk.models.mana_v2_app.manaV2App(
                        description = 'example string', 
                        identifier = graphiant_sdk.models.mana_v2_app_identifier.manaV2AppIdentifier(
                            id = 1234567891011, 
                            type = 'ENUM_VALUE', ), 
                        name = 'example string', )
                    ]
            )
        else:
            return V1GlobalAppsCategoriesCategoryIdAppsGetResponse(
        )
        """

    def testV1GlobalAppsCategoriesCategoryIdAppsGetResponse(self):
        """Test V1GlobalAppsCategoriesCategoryIdAppsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
