# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_devices_session_status_post_response import V1DevicesSessionStatusPostResponse

class TestV1DevicesSessionStatusPostResponse(unittest.TestCase):
    """V1DevicesSessionStatusPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DevicesSessionStatusPostResponse:
        """Test V1DevicesSessionStatusPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DevicesSessionStatusPostResponse`
        """
        model = V1DevicesSessionStatusPostResponse()
        if include_optional:
            return V1DevicesSessionStatusPostResponse(
                bgp_session_data_map = {
                    'key' : graphiant_sdk.models.v1_devices_session_status_post_response_data.v1DevicesSessionStatusPostResponseData(
                        core_bgp_neighbors_count = 123, 
                        device_id = 1234567891011, 
                        odp_bgp_neighbors_count = 123, 
                        wan_interfaces_count = 123, )
                    },
                bgp_session_map = {
                    'key' : graphiant_sdk.models.v1_devices_session_status_post_response_data.v1DevicesSessionStatusPostResponseData(
                        core_bgp_neighbors_count = 123, 
                        device_id = 1234567891011, 
                        odp_bgp_neighbors_count = 123, 
                        wan_interfaces_count = 123, )
                    },
                bgp_session_states = [
                    graphiant_sdk.models.v1_devices_session_status_post_response_data.v1DevicesSessionStatusPostResponseData(
                        core_bgp_neighbors_count = 123, 
                        device_id = 1234567891011, 
                        odp_bgp_neighbors_count = 123, 
                        wan_interfaces_count = 123, )
                    ]
            )
        else:
            return V1DevicesSessionStatusPostResponse(
        )
        """

    def testV1DevicesSessionStatusPostResponse(self):
        """Test V1DevicesSessionStatusPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
