# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_global_summary_post_request import V1GlobalSummaryPostRequest

class TestV1GlobalSummaryPostRequest(unittest.TestCase):
    """V1GlobalSummaryPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GlobalSummaryPostRequest:
        """Test V1GlobalSummaryPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GlobalSummaryPostRequest`
        """
        model = V1GlobalSummaryPostRequest()
        if include_optional:
            return V1GlobalSummaryPostRequest(
                ipfix_exported_type = True,
                prefix_set_type = True,
                routing_policy_type = True,
                snmp_type = True,
                syslog_server_type = True,
                traffic_policy_type = True
            )
        else:
            return V1GlobalSummaryPostRequest(
        )
        """

    def testV1GlobalSummaryPostRequest(self):
        """Test V1GlobalSummaryPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
