# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_interface_vlan_config import ManaV2InterfaceVlanConfig

class TestManaV2InterfaceVlanConfig(unittest.TestCase):
    """ManaV2InterfaceVlanConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2InterfaceVlanConfig:
        """Test ManaV2InterfaceVlanConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2InterfaceVlanConfig`
        """
        model = ManaV2InterfaceVlanConfig()
        if include_optional:
            return ManaV2InterfaceVlanConfig(
                admin_status = True,
                alias = 'example string',
                circuit = 'example string',
                description = 'example string',
                ipv4 = graphiant_sdk.models.mana_v2_interface_ip_config.manaV2InterfaceIpConfig(
                    address = graphiant_sdk.models.mana_v2_nullable_address.manaV2NullableAddress(), 
                    dhcp = graphiant_sdk.models.mana_v2_interface_dhcp_config.manaV2InterfaceDhcpConfig(
                        dhcp_client = True, 
                        dhcp_relay = graphiant_sdk.models.mana_v2_dhcp_relay_config.manaV2DhcpRelayConfig(
                            relay_servers = [
                                'example string'
                                ], ), ), 
                    vrrp = graphiant_sdk.models.mana_v2_nullable_vrrp_group_config.manaV2NullableVrrpGroupConfig(
                        group = graphiant_sdk.models.mana_v2_vrrp_group_config.manaV2VrrpGroupConfig(
                            accept_mode = True, 
                            allow_inter_operability = True, 
                            description = 'example string', 
                            enabled = True, 
                            preempt = True, 
                            priority = 123, 
                            tracked_interfaces = [
                                graphiant_sdk.models.mana_v2_nullable_interface_priority_decrement.manaV2NullableInterfacePriorityDecrement(
                                    interface = 'example string', 
                                    priority_decrement = 123, )
                                ], 
                            virtual_ip = 'example string', 
                            virtual_router_id = 123, ), ), ),
                ipv6 = graphiant_sdk.models.mana_v2_interface_ip_config.manaV2InterfaceIpConfig(
                    address = graphiant_sdk.models.mana_v2_nullable_address.manaV2NullableAddress(), 
                    dhcp = graphiant_sdk.models.mana_v2_interface_dhcp_config.manaV2InterfaceDhcpConfig(
                        dhcp_client = True, 
                        dhcp_relay = graphiant_sdk.models.mana_v2_dhcp_relay_config.manaV2DhcpRelayConfig(
                            relay_servers = [
                                'example string'
                                ], ), ), 
                    vrrp = graphiant_sdk.models.mana_v2_nullable_vrrp_group_config.manaV2NullableVrrpGroupConfig(
                        group = graphiant_sdk.models.mana_v2_vrrp_group_config.manaV2VrrpGroupConfig(
                            accept_mode = True, 
                            allow_inter_operability = True, 
                            description = 'example string', 
                            enabled = True, 
                            preempt = True, 
                            priority = 123, 
                            tracked_interfaces = [
                                graphiant_sdk.models.mana_v2_nullable_interface_priority_decrement.manaV2NullableInterfacePriorityDecrement(
                                    interface = 'example string', 
                                    priority_decrement = 123, )
                                ], 
                            virtual_ip = 'example string', 
                            virtual_router_id = 123, ), ), ),
                lan = 'example string',
                lldp_enabled = True,
                max_transmission_unit = 123,
                security_zone = 'example string',
                tcp_mss = 123,
                tcp_mss_v4 = 123,
                tcp_mss_v6 = 123,
                v4_tcp_mss = graphiant_sdk.models.mana_v2_nullable_tcp_mss_v4.manaV2NullableTcpMssV4(
                    tcp_mss_v4 = 123, ),
                v6_tcp_mss = graphiant_sdk.models.mana_v2_nullable_tcp_mss_v6.manaV2NullableTcpMssV6(
                    tcp_mss_v6 = 123, ),
                vlan = 123,
                vrrp = graphiant_sdk.models.mana_v2_nullable_vrrp_group_config.manaV2NullableVrrpGroupConfig(
                    group = graphiant_sdk.models.mana_v2_vrrp_group_config.manaV2VrrpGroupConfig(
                        accept_mode = True, 
                        allow_inter_operability = True, 
                        description = 'example string', 
                        enabled = True, 
                        preempt = True, 
                        priority = 123, 
                        tracked_interfaces = [
                            graphiant_sdk.models.mana_v2_nullable_interface_priority_decrement.manaV2NullableInterfacePriorityDecrement(
                                interface = 'example string', 
                                priority_decrement = 123, )
                            ], 
                        virtual_ip = 'example string', 
                        virtual_router_id = 123, ), )
            )
        else:
            return ManaV2InterfaceVlanConfig(
        )
        """

    def testManaV2InterfaceVlanConfig(self):
        """Test ManaV2InterfaceVlanConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
