# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_site_id_details_interfaces_get_response import V1SiteIdDetailsInterfacesGetResponse

class TestV1SiteIdDetailsInterfacesGetResponse(unittest.TestCase):
    """V1SiteIdDetailsInterfacesGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SiteIdDetailsInterfacesGetResponse:
        """Test V1SiteIdDetailsInterfacesGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SiteIdDetailsInterfacesGetResponse`
        """
        model = V1SiteIdDetailsInterfacesGetResponse()
        if include_optional:
            return V1SiteIdDetailsInterfacesGetResponse(
                interfaces = [
                    'example string'
                    ]
            )
        else:
            return V1SiteIdDetailsInterfacesGetResponse(
        )
        """

    def testV1SiteIdDetailsInterfacesGetResponse(self):
        """Test V1SiteIdDetailsInterfacesGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
