# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_global_syslogs_post_response import V1GlobalSyslogsPostResponse

class TestV1GlobalSyslogsPostResponse(unittest.TestCase):
    """V1GlobalSyslogsPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GlobalSyslogsPostResponse:
        """Test V1GlobalSyslogsPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GlobalSyslogsPostResponse`
        """
        model = V1GlobalSyslogsPostResponse()
        if include_optional:
            return V1GlobalSyslogsPostResponse(
                collectors = [
                    graphiant_sdk.models.mana_v2_syslog_collector.manaV2SyslogCollector(
                        destination_host = 'example string', 
                        destination_port = 123, 
                        enabled = True, 
                        error_message = 'example string', 
                        global_id = 1234567891011, 
                        id = 1234567891011, 
                        name = 'example string', 
                        severity = 'ENUM_VALUE', 
                        source_interface = 'example string', 
                        status = 'ENUM_VALUE', 
                        transport = 'ENUM_VALUE', 
                        vrf_id = 1234567891011, 
                        vrf_name = 'example string', )
                    ]
            )
        else:
            return V1GlobalSyslogsPostResponse(
        )
        """

    def testV1GlobalSyslogsPostResponse(self):
        """Test V1GlobalSyslogsPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
