# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.statsmon_v2_circuit_bandwidth_stats_selector import StatsmonV2CircuitBandwidthStatsSelector

class TestStatsmonV2CircuitBandwidthStatsSelector(unittest.TestCase):
    """StatsmonV2CircuitBandwidthStatsSelector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsmonV2CircuitBandwidthStatsSelector:
        """Test StatsmonV2CircuitBandwidthStatsSelector
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsmonV2CircuitBandwidthStatsSelector`
        """
        model = StatsmonV2CircuitBandwidthStatsSelector()
        if include_optional:
            return StatsmonV2CircuitBandwidthStatsSelector(
                circuit_name = 'example string',
                device_id = 12345678910
            )
        else:
            return StatsmonV2CircuitBandwidthStatsSelector(
        )
        """

    def testStatsmonV2CircuitBandwidthStatsSelector(self):
        """Test StatsmonV2CircuitBandwidthStatsSelector"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
