# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_assistant_conversation_context_history_post_request import V2AssistantConversationContextHistoryPostRequest

class TestV2AssistantConversationContextHistoryPostRequest(unittest.TestCase):
    """V2AssistantConversationContextHistoryPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2AssistantConversationContextHistoryPostRequest:
        """Test V2AssistantConversationContextHistoryPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2AssistantConversationContextHistoryPostRequest`
        """
        model = V2AssistantConversationContextHistoryPostRequest()
        if include_optional:
            return V2AssistantConversationContextHistoryPostRequest(
                enable = True
            )
        else:
            return V2AssistantConversationContextHistoryPostRequest(
        )
        """

    def testV2AssistantConversationContextHistoryPostRequest(self):
        """Test V2AssistantConversationContextHistoryPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
