# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_prometheus_config import ManaV2PrometheusConfig

class TestManaV2PrometheusConfig(unittest.TestCase):
    """ManaV2PrometheusConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2PrometheusConfig:
        """Test ManaV2PrometheusConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2PrometheusConfig`
        """
        model = ManaV2PrometheusConfig()
        if include_optional:
            return ManaV2PrometheusConfig(
                rule_groups = {
                    'key' : graphiant_sdk.models.mana_v2_nullable_prometheus_rule_group_config.manaV2NullablePrometheusRuleGroupConfig(
                        rule_group = graphiant_sdk.models.mana_v2_prometheus_rule_group_config.manaV2PrometheusRuleGroupConfig(
                            description = 'example string', 
                            interval_seconds = 123, 
                            name = 'example string', 
                            rules = {
                                'key' : graphiant_sdk.models.mana_v2_nullable_prometheus_rule_config.manaV2NullablePrometheusRuleConfig()
                                }, ), )
                    },
                sink = graphiant_sdk.models.mana_v2_nullable_prometheus_remote_write_sink_config.manaV2NullablePrometheusRemoteWriteSinkConfig(),
                sysdb_monitors = {
                    'key' : graphiant_sdk.models.mana_v2_nullable_prometheus_sys_db_monitor_config.manaV2NullablePrometheusSysDbMonitorConfig(
                        sysdb_monitor = graphiant_sdk.models.mana_v2_prometheus_sys_db_monitor_config.manaV2PrometheusSysDbMonitorConfig(
                            interval_seconds = 123, 
                            name = 'example string', 
                            xpaths = [
                                'example string'
                                ], ), )
                    }
            )
        else:
            return ManaV2PrometheusConfig(
        )
        """

    def testManaV2PrometheusConfig(self):
        """Test ManaV2PrometheusConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
