# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_notificationlist_post_response import V2NotificationlistPostResponse

class TestV2NotificationlistPostResponse(unittest.TestCase):
    """V2NotificationlistPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2NotificationlistPostResponse:
        """Test V2NotificationlistPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2NotificationlistPostResponse`
        """
        model = V2NotificationlistPostResponse()
        if include_optional:
            return V2NotificationlistPostResponse(
                notification_list = [
                    graphiant_sdk.models.alertservice_notification_record.alertserviceNotificationRecord(
                        alert_type = 'example string', 
                        mute_count = 1234567891011, 
                        name = 'example string', 
                        notification_body = graphiant_sdk.models.alertservice_notification_body.alertserviceNotificationBody(
                            description = 'example string', 
                            duration = 'ENUM_VALUE', 
                            enabled = True, 
                            frequency = 12345678910, 
                            message_body = 'example string', 
                            notification_name = 'example string', 
                            opsgenie_list = [
                                'example string'
                                ], 
                            opsramp_list = [
                                'example string'
                                ], 
                            recipient_list = [
                                'example string'
                                ], 
                            teams_list = [
                                'example string'
                                ], ), 
                        notification_id = 'example string', 
                        rule_id = 'example string', 
                        times_triggered = 12345678910, )
                    ]
            )
        else:
            return V2NotificationlistPostResponse(
        )
        """

    def testV2NotificationlistPostResponse(self):
        """Test V2NotificationlistPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
