# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.alarms_alarm_data import AlarmsAlarmData

class TestAlarmsAlarmData(unittest.TestCase):
    """AlarmsAlarmData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlarmsAlarmData:
        """Test AlarmsAlarmData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlarmsAlarmData`
        """
        model = AlarmsAlarmData()
        if include_optional:
            return AlarmsAlarmData(
                acknowledged_by = '8a2ec658-f25b-11ec-b939-0242ac120002',
                alarm_id = 10000,
                alarm_type_id = 'graphnos-systemd:systemd-unit-state-change',
                alarm_type_qualifier = 'example string',
                alt_component = 'example string',
                boot_id = '8a2ec658-f25b-11ec-b939-0242ac120002',
                component = 'graphnos-ntp-mgr.service',
                created = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, ),
                description = 'Unit is now active',
                is_cleared = False,
                is_resolved = False,
                last_changed = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, ),
                last_raised = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, ),
                perceived_severity = 'warning',
                resolved_by = '8a2ec658-f25b-11ec-b939-0242ac120002',
                sequence_number = 10,
                where = 'edge-32'
            )
        else:
            return AlarmsAlarmData(
        )
        """

    def testAlarmsAlarmData(self):
        """Test AlarmsAlarmData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
