# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_devices_upgrade_schedule_put_request import V1DevicesUpgradeSchedulePutRequest

class TestV1DevicesUpgradeSchedulePutRequest(unittest.TestCase):
    """V1DevicesUpgradeSchedulePutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DevicesUpgradeSchedulePutRequest:
        """Test V1DevicesUpgradeSchedulePutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DevicesUpgradeSchedulePutRequest`
        """
        model = V1DevicesUpgradeSchedulePutRequest()
        if include_optional:
            return V1DevicesUpgradeSchedulePutRequest(
                action = 'ENUM_VALUE',
                device_ids = [
                    1234567891011
                    ],
                device_versions = [
                    graphiant_sdk.models.v1_devices_upgrade_schedule_put_request_device_version.v1DevicesUpgradeSchedulePutRequestDeviceVersion(
                        device_id = 1234567891011, 
                        version = graphiant_sdk.models.upgrade_sw_version.upgradeSwVersion(
                            name = 'example string', 
                            release = 'ENUM_VALUE', ), )
                    ],
                ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, ),
                version = graphiant_sdk.models.upgrade_sw_version.upgradeSwVersion(
                    name = 'example string', 
                    release = 'ENUM_VALUE', 
                    version = 'example string', )
            )
        else:
            return V1DevicesUpgradeSchedulePutRequest(
        )
        """

    def testV1DevicesUpgradeSchedulePutRequest(self):
        """Test V1DevicesUpgradeSchedulePutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
