# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_enterprise_prefix_set_input_entry import ManaV2EnterprisePrefixSetInputEntry

class TestManaV2EnterprisePrefixSetInputEntry(unittest.TestCase):
    """ManaV2EnterprisePrefixSetInputEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2EnterprisePrefixSetInputEntry:
        """Test ManaV2EnterprisePrefixSetInputEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2EnterprisePrefixSetInputEntry`
        """
        model = ManaV2EnterprisePrefixSetInputEntry()
        if include_optional:
            return ManaV2EnterprisePrefixSetInputEntry(
                ip_prefix = 'example string',
                mask_lower = 123,
                mask_upper = 123,
                seq = 123
            )
        else:
            return ManaV2EnterprisePrefixSetInputEntry(
        )
        """

    def testManaV2EnterprisePrefixSetInputEntry(self):
        """Test ManaV2EnterprisePrefixSetInputEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
