# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_portal_apikeys_post_response import V1PortalApikeysPostResponse

class TestV1PortalApikeysPostResponse(unittest.TestCase):
    """V1PortalApikeysPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1PortalApikeysPostResponse:
        """Test V1PortalApikeysPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1PortalApikeysPostResponse`
        """
        model = V1PortalApikeysPostResponse()
        if include_optional:
            return V1PortalApikeysPostResponse(
                api_key = 'example string'
            )
        else:
            return V1PortalApikeysPostResponse(
        )
        """

    def testV1PortalApikeysPostResponse(self):
        """Test V1PortalApikeysPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
