# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.assurance_topology_filter import AssuranceTopologyFilter

class TestAssuranceTopologyFilter(unittest.TestCase):
    """AssuranceTopologyFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssuranceTopologyFilter:
        """Test AssuranceTopologyFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssuranceTopologyFilter`
        """
        model = AssuranceTopologyFilter()
        if include_optional:
            return AssuranceTopologyFilter(
                client_site_ids = [
                    1234567891011
                    ],
                region_ids = [
                    123
                    ],
                server_site_ids = [
                    1234567891011
                    ]
            )
        else:
            return AssuranceTopologyFilter(
        )
        """

    def testAssuranceTopologyFilter(self):
        """Test AssuranceTopologyFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
