# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_diagnostic_speedtest_providers_get_response import V1DiagnosticSpeedtestProvidersGetResponse

class TestV1DiagnosticSpeedtestProvidersGetResponse(unittest.TestCase):
    """V1DiagnosticSpeedtestProvidersGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DiagnosticSpeedtestProvidersGetResponse:
        """Test V1DiagnosticSpeedtestProvidersGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DiagnosticSpeedtestProvidersGetResponse`
        """
        model = V1DiagnosticSpeedtestProvidersGetResponse()
        if include_optional:
            return V1DiagnosticSpeedtestProvidersGetResponse(
                provider = [
                    'Ookla'
                    ]
            )
        else:
            return V1DiagnosticSpeedtestProvidersGetResponse(
        )
        """

    def testV1DiagnosticSpeedtestProvidersGetResponse(self):
        """Test V1DiagnosticSpeedtestProvidersGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
