# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_assurance_topology_flows_post_response import V2AssuranceTopologyFlowsPostResponse

class TestV2AssuranceTopologyFlowsPostResponse(unittest.TestCase):
    """V2AssuranceTopologyFlowsPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2AssuranceTopologyFlowsPostResponse:
        """Test V2AssuranceTopologyFlowsPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2AssuranceTopologyFlowsPostResponse`
        """
        model = V2AssuranceTopologyFlowsPostResponse()
        if include_optional:
            return V2AssuranceTopologyFlowsPostResponse(
                flows = [
                    graphiant_sdk.models.assurance_application_flow.assuranceApplicationFlow(
                        app_name = 'example string', 
                        client_ip = 'example string', 
                        client_site = graphiant_sdk.models.assurance_site.assuranceSite(
                            region_id = 123, 
                            site_id = 1234567891011, 
                            site_name = 'example string', ), 
                        first_seen_ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), 
                        lan_segment = 'example string', 
                        last_seen_ts = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), 
                        server_ip = 'example string', 
                        server_port = 123, 
                        server_site = graphiant_sdk.models.assurance_site.assuranceSite(
                            region_id = 123, 
                            site_id = 1234567891011, 
                            site_name = 'example string', ), )
                    ]
            )
        else:
            return V2AssuranceTopologyFlowsPostResponse(
        )
        """

    def testV2AssuranceTopologyFlowsPostResponse(self):
        """Test V2AssuranceTopologyFlowsPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
