# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_troubleshooting_enterprise_post_response_site_summary import V1TroubleshootingEnterprisePostResponseSiteSummary

class TestV1TroubleshootingEnterprisePostResponseSiteSummary(unittest.TestCase):
    """V1TroubleshootingEnterprisePostResponseSiteSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1TroubleshootingEnterprisePostResponseSiteSummary:
        """Test V1TroubleshootingEnterprisePostResponseSiteSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1TroubleshootingEnterprisePostResponseSiteSummary`
        """
        model = V1TroubleshootingEnterprisePostResponseSiteSummary()
        if include_optional:
            return V1TroubleshootingEnterprisePostResponseSiteSummary(
                control_status = 'ENUM_VALUE',
                data_status = 'ENUM_VALUE',
                overall_status = 'ENUM_VALUE',
                region = graphiant_sdk.models.statsmon_troubleshooting_region.statsmonTroubleshootingRegion(
                    region_id = 123, 
                    region_name = 'example string', ),
                selected_status = 'ENUM_VALUE',
                site_id = 1234567891011,
                site_name = 'example string',
                system_status = 'ENUM_VALUE'
            )
        else:
            return V1TroubleshootingEnterprisePostResponseSiteSummary(
        )
        """

    def testV1TroubleshootingEnterprisePostResponseSiteSummary(self):
        """Test V1TroubleshootingEnterprisePostResponseSiteSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
