# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_b2b_application_customer_summary import ManaV2B2bApplicationCustomerSummary

class TestManaV2B2bApplicationCustomerSummary(unittest.TestCase):
    """ManaV2B2bApplicationCustomerSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2B2bApplicationCustomerSummary:
        """Test ManaV2B2bApplicationCustomerSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2B2bApplicationCustomerSummary`
        """
        model = ManaV2B2bApplicationCustomerSummary()
        if include_optional:
            return ManaV2B2bApplicationCustomerSummary(
                admin_email = 'example string',
                enterprise_id = 1234567891011,
                id = 1234567891011,
                name = 'example string',
                status = 'ENUM_VALUE',
                updated_at = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                    nanos = 123, 
                    seconds = 1234567891011, )
            )
        else:
            return ManaV2B2bApplicationCustomerSummary(
        )
        """

    def testManaV2B2bApplicationCustomerSummary(self):
        """Test ManaV2B2bApplicationCustomerSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
