# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_diagnostic_reset_ipsec_session_device_id_put_request import V1DiagnosticResetIpsecSessionDeviceIdPutRequest

class TestV1DiagnosticResetIpsecSessionDeviceIdPutRequest(unittest.TestCase):
    """V1DiagnosticResetIpsecSessionDeviceIdPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DiagnosticResetIpsecSessionDeviceIdPutRequest:
        """Test V1DiagnosticResetIpsecSessionDeviceIdPutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DiagnosticResetIpsecSessionDeviceIdPutRequest`
        """
        model = V1DiagnosticResetIpsecSessionDeviceIdPutRequest()
        if include_optional:
            return V1DiagnosticResetIpsecSessionDeviceIdPutRequest(
                all3_rd_party = True,
                all_controllers = True,
                all_e2_e = True,
                vrf = [
                    'isp-11, isp-12'
                    ]
            )
        else:
            return V1DiagnosticResetIpsecSessionDeviceIdPutRequest(
        )
        """

    def testV1DiagnosticResetIpsecSessionDeviceIdPutRequest(self):
        """Test V1DiagnosticResetIpsecSessionDeviceIdPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
