# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_routing_policy_config_nullable_statement_statement_nullable_action import ManaV2RoutingPolicyConfigNullableStatementStatementNullableAction

class TestManaV2RoutingPolicyConfigNullableStatementStatementNullableAction(unittest.TestCase):
    """ManaV2RoutingPolicyConfigNullableStatementStatementNullableAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2RoutingPolicyConfigNullableStatementStatementNullableAction:
        """Test ManaV2RoutingPolicyConfigNullableStatementStatementNullableAction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2RoutingPolicyConfigNullableStatementStatementNullableAction`
        """
        model = ManaV2RoutingPolicyConfigNullableStatementStatementNullableAction()
        if include_optional:
            return ManaV2RoutingPolicyConfigNullableStatementStatementNullableAction(
                action = graphiant_sdk.models.mana_v2_routing_policy_config_nullable_statement_statement_nullable_action_action.manaV2RoutingPolicyConfigNullableStatementStatementNullableActionAction(
                    administrative_distance = graphiant_sdk.models.mana_v2_nullable_administrative_distance.manaV2NullableAdministrativeDistance(
                        distance = 123, ), 
                    aspath_prepend = graphiant_sdk.models.mana_v2_nullable_as_path_prepend.manaV2NullableAsPathPrepend(
                        repeat = 123, ), 
                    bgp_set_next_hop = graphiant_sdk.models.mana_v2_nullable_bgp_set_next_hop.manaV2NullableBgpSetNextHop(
                        next_hop = 'example string', ), 
                    call_policy = graphiant_sdk.models.mana_v2_nullable_call_policy.manaV2NullableCallPolicy(
                        policy = 'example string', ), 
                    communities = graphiant_sdk.models.mana_v2_nullable_communities.manaV2NullableCommunities(
                        community = graphiant_sdk.models.mana_v2_community_type.manaV2CommunityType(
                            additive = True, 
                            community_list = [
                                'example string'
                                ], ), ), 
                    local_pref = graphiant_sdk.models.mana_v2_nullable_local_preferance.manaV2NullableLocalPreferance(), 
                    metric = graphiant_sdk.models.mana_v2_nullable_metric.manaV2NullableMetric(
                        absolute = 123, 
                        modifier = 123, ), 
                    result = 'ENUM_VALUE', 
                    seq = 123, 
                    weight = graphiant_sdk.models.mana_v2_nullable_weight.manaV2NullableWeight(), )
            )
        else:
            return ManaV2RoutingPolicyConfigNullableStatementStatementNullableAction(
        )
        """

    def testManaV2RoutingPolicyConfigNullableStatementStatementNullableAction(self):
        """Test ManaV2RoutingPolicyConfigNullableStatementStatementNullableAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
