# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_assistant_add_to_conversation_post_response import V2AssistantAddToConversationPostResponse

class TestV2AssistantAddToConversationPostResponse(unittest.TestCase):
    """V2AssistantAddToConversationPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2AssistantAddToConversationPostResponse:
        """Test V2AssistantAddToConversationPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2AssistantAddToConversationPostResponse`
        """
        model = V2AssistantAddToConversationPostResponse()
        if include_optional:
            return V2AssistantAddToConversationPostResponse(
                conversation_id = 'example string',
                dataframe_dictionary = [
                    graphiant_sdk.models.assistant_dataframe_dictionary.assistantDataframeDictionary(
                        dataframe_dictionary_map = {
                            'key' : 'example string'
                            }, 
                        x_axis = 'example string', 
                        y_axis = 'example string', )
                    ],
                original_question = graphiant_sdk.models.assistant_assistant_question.assistantAssistantQuestion(
                    conversation_id = 'example string', 
                    question_language = 'ENUM_VALUE', 
                    question_text = 'example string', 
                    question_timestamp = 1234567891011, ),
                response_id = 'example string',
                response_language = 'ENUM_VALUE',
                response_text = 'example string',
                response_timestamp = 1234567891011,
                response_type = 'ENUM_VALUE',
                visualization_summary = 'example string'
            )
        else:
            return V2AssistantAddToConversationPostResponse(
        )
        """

    def testV2AssistantAddToConversationPostResponse(self):
        """Test V2AssistantAddToConversationPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
