# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_bwtracker_enterprise_details_post_response import V1BwtrackerEnterpriseDetailsPostResponse

class TestV1BwtrackerEnterpriseDetailsPostResponse(unittest.TestCase):
    """V1BwtrackerEnterpriseDetailsPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1BwtrackerEnterpriseDetailsPostResponse:
        """Test V1BwtrackerEnterpriseDetailsPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1BwtrackerEnterpriseDetailsPostResponse`
        """
        model = V1BwtrackerEnterpriseDetailsPostResponse()
        if include_optional:
            return V1BwtrackerEnterpriseDetailsPostResponse(
                bwusage_details = graphiant_sdk.models.statsmon_bandwidthtracker_bw_usage_by_enterprise_details.statsmonBandwidthtrackerBwUsageByEnterpriseDetails(
                    bwusage_region = [
                        graphiant_sdk.models.statsmon_bandwidthtracker_bw_usage_by_region.statsmonBandwidthtrackerBwUsageByRegion(
                            region_id = 12345678910, 
                            region_name = 'example string', 
                            site_count = 12345678910, 
                            usage_kbps = 123.45, )
                        ], 
                    bwusage_site = [
                        graphiant_sdk.models.statsmon_bandwidthtracker_bw_usage_by_site.statsmonBandwidthtrackerBwUsageBySite(
                            edge_count = 12345678910, 
                            location_id = 12345678910, 
                            location_name = 'example string', 
                            site_id = 12345678910, 
                            site_name = 'example string', 
                            usage_kbps = 123.45, )
                        ], 
                    bwusage_site_gateway = [
                        graphiant_sdk.models.statsmon_bandwidthtracker_bw_usage_by_site.statsmonBandwidthtrackerBwUsageBySite(
                            edge_count = 12345678910, 
                            location_id = 12345678910, 
                            location_name = 'example string', 
                            site_id = 12345678910, 
                            site_name = 'example string', 
                            usage_kbps = 123.45, )
                        ], )
            )
        else:
            return V1BwtrackerEnterpriseDetailsPostResponse(
        )
        """

    def testV1BwtrackerEnterpriseDetailsPostResponse(self):
        """Test V1BwtrackerEnterpriseDetailsPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
