# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_qo_s_profile import ManaV2QoSProfile

class TestManaV2QoSProfile(unittest.TestCase):
    """ManaV2QoSProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2QoSProfile:
        """Test ManaV2QoSProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2QoSProfile`
        """
        model = ManaV2QoSProfile()
        if include_optional:
            return ManaV2QoSProfile(
                kind = 'ENUM_VALUE',
                profile = 'ENUM_VALUE',
                queues = [
                    graphiant_sdk.models.mana_v2_qo_s_profile_queue.manaV2QoSProfileQueue(
                        bandwidth_percent = 123, 
                        default_queue = True, 
                        sla_class = 'ENUM_VALUE', )
                    ]
            )
        else:
            return ManaV2QoSProfile(
        )
        """

    def testManaV2QoSProfile(self):
        """Test ManaV2QoSProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
