# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_global_object_operation_config import ManaV2GlobalObjectOperationConfig

class TestManaV2GlobalObjectOperationConfig(unittest.TestCase):
    """ManaV2GlobalObjectOperationConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2GlobalObjectOperationConfig:
        """Test ManaV2GlobalObjectOperationConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2GlobalObjectOperationConfig`
        """
        model = ManaV2GlobalObjectOperationConfig()
        if include_optional:
            return ManaV2GlobalObjectOperationConfig(
                interface = graphiant_sdk.models.mana_v2_nullable_site_interface_name.manaV2NullableSiteInterfaceName(),
                operation = 'ENUM_VALUE'
            )
        else:
            return ManaV2GlobalObjectOperationConfig(
        )
        """

    def testManaV2GlobalObjectOperationConfig(self):
        """Test ManaV2GlobalObjectOperationConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
