# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_policy_route_tag_sets_post_response import V1PolicyRouteTagSetsPostResponse

class TestV1PolicyRouteTagSetsPostResponse(unittest.TestCase):
    """V1PolicyRouteTagSetsPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1PolicyRouteTagSetsPostResponse:
        """Test V1PolicyRouteTagSetsPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1PolicyRouteTagSetsPostResponse`
        """
        model = V1PolicyRouteTagSetsPostResponse()
        if include_optional:
            return V1PolicyRouteTagSetsPostResponse(
                id = 1234567891011
            )
        else:
            return V1PolicyRouteTagSetsPostResponse(
        )
        """

    def testV1PolicyRouteTagSetsPostResponse(self):
        """Test V1PolicyRouteTagSetsPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
