# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v1_devices_inventory_get_response import V1DevicesInventoryGetResponse

class TestV1DevicesInventoryGetResponse(unittest.TestCase):
    """V1DevicesInventoryGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DevicesInventoryGetResponse:
        """Test V1DevicesInventoryGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DevicesInventoryGetResponse`
        """
        model = V1DevicesInventoryGetResponse()
        if include_optional:
            return V1DevicesInventoryGetResponse(
                inventory = [
                    graphiant_sdk.models.onboarding_hardware_inventory.onboardingHardwareInventory(
                        assigned_on = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), 
                        created_on = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), 
                        device_model = 'example string', 
                        device_serial = 'example string', 
                        ek_cert = 'example string', 
                        enterprise_id = 1234567891011, 
                        enterprise_name = 'example string', 
                        gek_pub = 'example string', 
                        is_core = True, 
                        is_new = True, 
                        is_requested = True, 
                        parent_enterprise_id = 1234567891011, 
                        parent_enterprise_name = 'example string', 
                        role = 'ENUM_VALUE', 
                        use_oauth = True, 
                        uuid = 'example string', )
                    ],
                page_info = graphiant_sdk.models.common_page_info.commonPageInfo(
                    current_page = 1, 
                    end_cursor = 'xxxxxxy', 
                    has_next_page = False, 
                    has_prev_page = True, 
                    start_cursor = 'xxxxxx', 
                    total_pages = 4, 
                    total_records = 400, )
            )
        else:
            return V1DevicesInventoryGetResponse(
        )
        """

    def testV1DevicesInventoryGetResponse(self):
        """Test V1DevicesInventoryGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
