# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.v2_assurance_updateclassifiedapplication_post_request import V2AssuranceUpdateclassifiedapplicationPostRequest

class TestV2AssuranceUpdateclassifiedapplicationPostRequest(unittest.TestCase):
    """V2AssuranceUpdateclassifiedapplicationPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2AssuranceUpdateclassifiedapplicationPostRequest:
        """Test V2AssuranceUpdateclassifiedapplicationPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2AssuranceUpdateclassifiedapplicationPostRequest`
        """
        model = V2AssuranceUpdateclassifiedapplicationPostRequest()
        if include_optional:
            return V2AssuranceUpdateclassifiedapplicationPostRequest(
                classified_application_list = [
                    graphiant_sdk.models.assurance_classified_application.assuranceClassifiedApplication(
                        app_name = 'example string', 
                        classification_entry_id = 'example string', 
                        ip_prefix_list = [
                            'example string'
                            ], 
                        port_list = [
                            'example string'
                            ], 
                        protocol_list = [
                            'example string'
                            ], )
                    ]
            )
        else:
            return V2AssuranceUpdateclassifiedapplicationPostRequest(
        )
        """

    def testV2AssuranceUpdateclassifiedapplicationPostRequest(self):
        """Test V2AssuranceUpdateclassifiedapplicationPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
