# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from graphiant_sdk.models.mana_v2_dhcp_server_pool import ManaV2DhcpServerPool

class TestManaV2DhcpServerPool(unittest.TestCase):
    """ManaV2DhcpServerPool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManaV2DhcpServerPool:
        """Test ManaV2DhcpServerPool
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManaV2DhcpServerPool`
        """
        model = ManaV2DhcpServerPool()
        if include_optional:
            return ManaV2DhcpServerPool(
                default_lease_time_secs = 123,
                description = 'example string',
                domain_name = 'example string',
                gateway = 'example string',
                id = 1234567891011,
                interface = 'example string',
                ip_prefix = 'example string',
                ip_version = 123,
                leases = [
                    graphiant_sdk.models.mana_v2_dhcp_lease.manaV2DhcpLease(
                        ends_at = graphiant_sdk.models.google_protobuf_timestamp.googleProtobufTimestamp(
                            nanos = 123, 
                            seconds = 1234567891011, ), 
                        id = 1234567891011, 
                        ip_address = 'example string', 
                        mac_address = 'example string', 
                        vrf = 'example string', )
                    ],
                max_lease_time_secs = 123,
                min_lease_time_secs = 123,
                name = 'example string',
                nameservers = graphiant_sdk.models.mana_v2_dns_servers.manaV2DnsServers(
                    primary = 'example string', 
                    secondary = 'example string', ),
                ranges = [
                    graphiant_sdk.models.mana_v2_dhcp_server_ip_range.manaV2DhcpServerIpRange(
                        end = 'example string', 
                        start = 'example string', )
                    ],
                static_leases = [
                    graphiant_sdk.models.mana_v2_dhcp_static_lease.manaV2DhcpStaticLease(
                        hostname = 'example string', 
                        id = 1234567891011, 
                        ip_address = 'example string', 
                        mac_address = 'example string', 
                        vrf = 'example string', )
                    ],
                total_addresses = 12345678910,
                utilization = 123
            )
        else:
            return ManaV2DhcpServerPool(
        )
        """

    def testManaV2DhcpServerPool(self):
        """Test ManaV2DhcpServerPool"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
