# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.mana_v2_dnsip_address import ManaV2DnsipAddress
from typing import Optional, Set
from typing_extensions import Self

class ManaV2StaticDnsServers(BaseModel):
    """
    ManaV2StaticDnsServers
    """ # noqa: E501
    primary_ipv4_server: Optional[ManaV2DnsipAddress] = Field(default=None, alias="primaryIpv4Server")
    primary_ipv6_server: Optional[ManaV2DnsipAddress] = Field(default=None, alias="primaryIpv6Server")
    secondary_ipv4_server: Optional[ManaV2DnsipAddress] = Field(default=None, alias="secondaryIpv4Server")
    secondary_ipv6_server: Optional[ManaV2DnsipAddress] = Field(default=None, alias="secondaryIpv6Server")
    __properties: ClassVar[List[str]] = ["primaryIpv4Server", "primaryIpv6Server", "secondaryIpv4Server", "secondaryIpv6Server"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2StaticDnsServers from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of primary_ipv4_server
        if self.primary_ipv4_server:
            _dict['primaryIpv4Server'] = self.primary_ipv4_server.to_dict()
        # override the default output from pydantic by calling `to_dict()` of primary_ipv6_server
        if self.primary_ipv6_server:
            _dict['primaryIpv6Server'] = self.primary_ipv6_server.to_dict()
        # override the default output from pydantic by calling `to_dict()` of secondary_ipv4_server
        if self.secondary_ipv4_server:
            _dict['secondaryIpv4Server'] = self.secondary_ipv4_server.to_dict()
        # override the default output from pydantic by calling `to_dict()` of secondary_ipv6_server
        if self.secondary_ipv6_server:
            _dict['secondaryIpv6Server'] = self.secondary_ipv6_server.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2StaticDnsServers from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "primaryIpv4Server": ManaV2DnsipAddress.from_dict(obj["primaryIpv4Server"]) if obj.get("primaryIpv4Server") is not None else None,
            "primaryIpv6Server": ManaV2DnsipAddress.from_dict(obj["primaryIpv6Server"]) if obj.get("primaryIpv6Server") is not None else None,
            "secondaryIpv4Server": ManaV2DnsipAddress.from_dict(obj["secondaryIpv4Server"]) if obj.get("secondaryIpv4Server") is not None else None,
            "secondaryIpv6Server": ManaV2DnsipAddress.from_dict(obj["secondaryIpv6Server"]) if obj.get("secondaryIpv6Server") is not None else None
        })
        return _obj


