# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.mana_v2_nullable_ospf_interface_config import ManaV2NullableOspfInterfaceConfig
from typing import Optional, Set
from typing_extensions import Self

class ManaV2OspfAreaConfig(BaseModel):
    """
    ManaV2OspfAreaConfig
    """ # noqa: E501
    area_id: Optional[StrictStr] = Field(default=None, alias="areaId")
    interfaces: Optional[Dict[str, ManaV2NullableOspfInterfaceConfig]] = None
    name: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["areaId", "interfaces", "name", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManaV2OspfAreaConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in interfaces (dict)
        _field_dict = {}
        if self.interfaces:
            for _key_interfaces in self.interfaces:
                if self.interfaces[_key_interfaces]:
                    _field_dict[_key_interfaces] = self.interfaces[_key_interfaces].to_dict()
            _dict['interfaces'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManaV2OspfAreaConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "areaId": obj.get("areaId"),
            "interfaces": dict(
                (_k, ManaV2NullableOspfInterfaceConfig.from_dict(_v))
                for _k, _v in obj["interfaces"].items()
            )
            if obj.get("interfaces") is not None
            else None,
            "name": obj.get("name"),
            "type": obj.get("type")
        })
        return _obj


