# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from graphiant_sdk.models.statsmon_bandwidthtracker_bw_usage_by_top_providers import StatsmonBandwidthtrackerBwUsageByTopProviders
from typing import Optional, Set
from typing_extensions import Self

class StatsmonBandwidthtrackerBwUsageByRegionCloudSummary(BaseModel):
    """
    StatsmonBandwidthtrackerBwUsageByRegionCloudSummary
    """ # noqa: E501
    bwusage_top_providers: Optional[List[StatsmonBandwidthtrackerBwUsageByTopProviders]] = Field(default=None, alias="bwusageTopProviders")
    cloudusage_kbps: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="cloudusageKbps")
    percent_changed: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="percentChanged")
    provider_count: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="providerCount")
    providerusage_kbps: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="providerusageKbps")
    totusage_kbps: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="totusageKbps")
    __properties: ClassVar[List[str]] = ["bwusageTopProviders", "cloudusageKbps", "percentChanged", "providerCount", "providerusageKbps", "totusageKbps"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatsmonBandwidthtrackerBwUsageByRegionCloudSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in bwusage_top_providers (list)
        _items = []
        if self.bwusage_top_providers:
            for _item_bwusage_top_providers in self.bwusage_top_providers:
                if _item_bwusage_top_providers:
                    _items.append(_item_bwusage_top_providers.to_dict())
            _dict['bwusageTopProviders'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatsmonBandwidthtrackerBwUsageByRegionCloudSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bwusageTopProviders": [StatsmonBandwidthtrackerBwUsageByTopProviders.from_dict(_item) for _item in obj["bwusageTopProviders"]] if obj.get("bwusageTopProviders") is not None else None,
            "cloudusageKbps": obj.get("cloudusageKbps"),
            "percentChanged": obj.get("percentChanged"),
            "providerCount": obj.get("providerCount"),
            "providerusageKbps": obj.get("providerusageKbps"),
            "totusageKbps": obj.get("totusageKbps")
        })
        return _obj


