# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from graphiant_sdk.models.auditmon_activity_logs_selector import AuditmonActivityLogsSelector
from graphiant_sdk.models.auditmon_activity_logs_selector_v2 import AuditmonActivityLogsSelectorV2
from graphiant_sdk.models.google_protobuf_timestamp import GoogleProtobufTimestamp
from typing import Optional, Set
from typing_extensions import Self

class V1ActivityLogsPostRequest(BaseModel):
    """
    V1ActivityLogsPostRequest
    """ # noqa: E501
    cursor_ref: Optional[StrictStr] = Field(default=None, alias="cursorRef")
    num_logs: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="numLogs")
    old_ts: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="oldTs")
    recent_ts: Optional[GoogleProtobufTimestamp] = Field(default=None, alias="recentTs")
    selector: Optional[AuditmonActivityLogsSelector] = None
    selector_v2: Optional[AuditmonActivityLogsSelectorV2] = Field(default=None, alias="selectorV2")
    __properties: ClassVar[List[str]] = ["cursorRef", "numLogs", "oldTs", "recentTs", "selector", "selectorV2"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1ActivityLogsPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of old_ts
        if self.old_ts:
            _dict['oldTs'] = self.old_ts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of recent_ts
        if self.recent_ts:
            _dict['recentTs'] = self.recent_ts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of selector
        if self.selector:
            _dict['selector'] = self.selector.to_dict()
        # override the default output from pydantic by calling `to_dict()` of selector_v2
        if self.selector_v2:
            _dict['selectorV2'] = self.selector_v2.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1ActivityLogsPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cursorRef": obj.get("cursorRef"),
            "numLogs": obj.get("numLogs"),
            "oldTs": GoogleProtobufTimestamp.from_dict(obj["oldTs"]) if obj.get("oldTs") is not None else None,
            "recentTs": GoogleProtobufTimestamp.from_dict(obj["recentTs"]) if obj.get("recentTs") is not None else None,
            "selector": AuditmonActivityLogsSelector.from_dict(obj["selector"]) if obj.get("selector") is not None else None,
            "selectorV2": AuditmonActivityLogsSelectorV2.from_dict(obj["selectorV2"]) if obj.get("selectorV2") is not None else None
        })
        return _obj


