# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class V1DiagnosticResetIpsecSessionDeviceIdPutRequest(BaseModel):
    """
    V1DiagnosticResetIpsecSessionDeviceIdPutRequest
    """ # noqa: E501
    all3_rd_party: Optional[StrictBool] = Field(default=None, description="All 3rd Party IPSec sessions", alias="all3RdParty")
    all_controllers: Optional[StrictBool] = Field(default=None, description="All Graphiant controllers IPSec sessions", alias="allControllers")
    all_e2_e: Optional[StrictBool] = Field(default=None, description="All Edge to Edge sessions", alias="allE2E")
    vrf: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["all3RdParty", "allControllers", "allE2E", "vrf"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1DiagnosticResetIpsecSessionDeviceIdPutRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1DiagnosticResetIpsecSessionDeviceIdPutRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "all3RdParty": obj.get("all3RdParty"),
            "allControllers": obj.get("allControllers"),
            "allE2E": obj.get("allE2E"),
            "vrf": obj.get("vrf")
        })
        return _obj


