# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.mana_v2_b2b_site_information import ManaV2B2bSiteInformation
from graphiant_sdk.models.mana_v2_extranet_consumer_lan_segment_policy import ManaV2ExtranetConsumerLanSegmentPolicy
from typing import Optional, Set
from typing_extensions import Self

class V1ExtranetsB2bConsumerPostRequest(BaseModel):
    """
    V1ExtranetsB2bConsumerPostRequest
    """ # noqa: E501
    policy: Optional[List[ManaV2ExtranetConsumerLanSegmentPolicy]] = None
    provider_enterprise_id: Optional[StrictInt] = Field(default=None, alias="providerEnterpriseId")
    service_name: Optional[StrictStr] = Field(default=None, alias="serviceName")
    site_information: Optional[List[ManaV2B2bSiteInformation]] = Field(default=None, alias="siteInformation")
    __properties: ClassVar[List[str]] = ["policy", "providerEnterpriseId", "serviceName", "siteInformation"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1ExtranetsB2bConsumerPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in policy (list)
        _items = []
        if self.policy:
            for _item_policy in self.policy:
                if _item_policy:
                    _items.append(_item_policy.to_dict())
            _dict['policy'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in site_information (list)
        _items = []
        if self.site_information:
            for _item_site_information in self.site_information:
                if _item_site_information:
                    _items.append(_item_site_information.to_dict())
            _dict['siteInformation'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1ExtranetsB2bConsumerPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "policy": [ManaV2ExtranetConsumerLanSegmentPolicy.from_dict(_item) for _item in obj["policy"]] if obj.get("policy") is not None else None,
            "providerEnterpriseId": obj.get("providerEnterpriseId"),
            "serviceName": obj.get("serviceName"),
            "siteInformation": [ManaV2B2bSiteInformation.from_dict(_item) for _item in obj["siteInformation"]] if obj.get("siteInformation") is not None else None
        })
        return _obj


