# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.mana_v2_b2b_extranet_peering_service_consumer_lan_segment_policy import ManaV2B2bExtranetPeeringServiceConsumerLanSegmentPolicy
from graphiant_sdk.models.mana_v2_b2b_extranet_service_customer_match_details import ManaV2B2bExtranetServiceCustomerMatchDetails
from graphiant_sdk.models.mana_v2_b2b_site_information import ManaV2B2bSiteInformation
from graphiant_sdk.models.mana_v2_global_object_service_summaries import ManaV2GlobalObjectServiceSummaries
from graphiant_sdk.models.mana_v2_guest_consumer_site_to_site_vpn_config import ManaV2GuestConsumerSiteToSiteVpnConfig
from graphiant_sdk.models.v1_extranets_b2b_peering_consumer_customer_id_consumer_details_get_response_ipsec_vpn_tunnel_config import V1ExtranetsB2bPeeringConsumerCustomerIdConsumerDetailsGetResponseIpsecVpnTunnelConfig
from typing import Optional, Set
from typing_extensions import Self

class V1ExtranetsB2bPeeringConsumerCustomerIdConsumerDetailsGetResponse(BaseModel):
    """
    V1ExtranetsB2bPeeringConsumerCustomerIdConsumerDetailsGetResponse
    """ # noqa: E501
    consumer_id: Optional[StrictInt] = Field(default=None, alias="consumerId")
    consumer_name: Optional[StrictStr] = Field(default=None, alias="consumerName")
    emails: Optional[List[StrictStr]] = None
    global_object_device_summaries: Optional[Dict[str, ManaV2GlobalObjectServiceSummaries]] = Field(default=None, alias="globalObjectDeviceSummaries")
    global_object_summaries: Optional[Dict[str, ManaV2GlobalObjectServiceSummaries]] = Field(default=None, alias="globalObjectSummaries")
    ipsec_tunnel_config: Optional[List[V1ExtranetsB2bPeeringConsumerCustomerIdConsumerDetailsGetResponseIpsecVpnTunnelConfig]] = Field(default=None, alias="ipsecTunnelConfig")
    match_details: Optional[ManaV2B2bExtranetServiceCustomerMatchDetails] = Field(default=None, alias="matchDetails")
    peer_type: Optional[StrictStr] = Field(default=None, alias="peerType")
    policy: Optional[List[ManaV2B2bExtranetPeeringServiceConsumerLanSegmentPolicy]] = None
    site_information: Optional[List[ManaV2B2bSiteInformation]] = Field(default=None, alias="siteInformation")
    site_to_site_vpn: Optional[ManaV2GuestConsumerSiteToSiteVpnConfig] = Field(default=None, alias="siteToSiteVpn")
    status: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["consumerId", "consumerName", "emails", "globalObjectDeviceSummaries", "globalObjectSummaries", "ipsecTunnelConfig", "matchDetails", "peerType", "policy", "siteInformation", "siteToSiteVpn", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1ExtranetsB2bPeeringConsumerCustomerIdConsumerDetailsGetResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in global_object_device_summaries (dict)
        _field_dict = {}
        if self.global_object_device_summaries:
            for _key_global_object_device_summaries in self.global_object_device_summaries:
                if self.global_object_device_summaries[_key_global_object_device_summaries]:
                    _field_dict[_key_global_object_device_summaries] = self.global_object_device_summaries[_key_global_object_device_summaries].to_dict()
            _dict['globalObjectDeviceSummaries'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in global_object_summaries (dict)
        _field_dict = {}
        if self.global_object_summaries:
            for _key_global_object_summaries in self.global_object_summaries:
                if self.global_object_summaries[_key_global_object_summaries]:
                    _field_dict[_key_global_object_summaries] = self.global_object_summaries[_key_global_object_summaries].to_dict()
            _dict['globalObjectSummaries'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in ipsec_tunnel_config (list)
        _items = []
        if self.ipsec_tunnel_config:
            for _item_ipsec_tunnel_config in self.ipsec_tunnel_config:
                if _item_ipsec_tunnel_config:
                    _items.append(_item_ipsec_tunnel_config.to_dict())
            _dict['ipsecTunnelConfig'] = _items
        # override the default output from pydantic by calling `to_dict()` of match_details
        if self.match_details:
            _dict['matchDetails'] = self.match_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in policy (list)
        _items = []
        if self.policy:
            for _item_policy in self.policy:
                if _item_policy:
                    _items.append(_item_policy.to_dict())
            _dict['policy'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in site_information (list)
        _items = []
        if self.site_information:
            for _item_site_information in self.site_information:
                if _item_site_information:
                    _items.append(_item_site_information.to_dict())
            _dict['siteInformation'] = _items
        # override the default output from pydantic by calling `to_dict()` of site_to_site_vpn
        if self.site_to_site_vpn:
            _dict['siteToSiteVpn'] = self.site_to_site_vpn.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1ExtranetsB2bPeeringConsumerCustomerIdConsumerDetailsGetResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "consumerId": obj.get("consumerId"),
            "consumerName": obj.get("consumerName"),
            "emails": obj.get("emails"),
            "globalObjectDeviceSummaries": dict(
                (_k, ManaV2GlobalObjectServiceSummaries.from_dict(_v))
                for _k, _v in obj["globalObjectDeviceSummaries"].items()
            )
            if obj.get("globalObjectDeviceSummaries") is not None
            else None,
            "globalObjectSummaries": dict(
                (_k, ManaV2GlobalObjectServiceSummaries.from_dict(_v))
                for _k, _v in obj["globalObjectSummaries"].items()
            )
            if obj.get("globalObjectSummaries") is not None
            else None,
            "ipsecTunnelConfig": [V1ExtranetsB2bPeeringConsumerCustomerIdConsumerDetailsGetResponseIpsecVpnTunnelConfig.from_dict(_item) for _item in obj["ipsecTunnelConfig"]] if obj.get("ipsecTunnelConfig") is not None else None,
            "matchDetails": ManaV2B2bExtranetServiceCustomerMatchDetails.from_dict(obj["matchDetails"]) if obj.get("matchDetails") is not None else None,
            "peerType": obj.get("peerType"),
            "policy": [ManaV2B2bExtranetPeeringServiceConsumerLanSegmentPolicy.from_dict(_item) for _item in obj["policy"]] if obj.get("policy") is not None else None,
            "siteInformation": [ManaV2B2bSiteInformation.from_dict(_item) for _item in obj["siteInformation"]] if obj.get("siteInformation") is not None else None,
            "siteToSiteVpn": ManaV2GuestConsumerSiteToSiteVpnConfig.from_dict(obj["siteToSiteVpn"]) if obj.get("siteToSiteVpn") is not None else None,
            "status": obj.get("status")
        })
        return _obj


