# coding: utf-8

"""
    Graphiant APIs

    Graphiant API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from graphiant_sdk.models.v1_troubleshooting_top_sites_by_alerts_post_response_site_counts import V1TroubleshootingTopSitesByAlertsPostResponseSiteCounts
from typing import Optional, Set
from typing_extensions import Self

class V1TroubleshootingTopSitesByAlertsPostResponse(BaseModel):
    """
    V1TroubleshootingTopSitesByAlertsPostResponse
    """ # noqa: E501
    control_plane: Optional[V1TroubleshootingTopSitesByAlertsPostResponseSiteCounts] = Field(default=None, alias="controlPlane")
    data_plane: Optional[V1TroubleshootingTopSitesByAlertsPostResponseSiteCounts] = Field(default=None, alias="dataPlane")
    system_plane: Optional[V1TroubleshootingTopSitesByAlertsPostResponseSiteCounts] = Field(default=None, alias="systemPlane")
    __properties: ClassVar[List[str]] = ["controlPlane", "dataPlane", "systemPlane"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1TroubleshootingTopSitesByAlertsPostResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of control_plane
        if self.control_plane:
            _dict['controlPlane'] = self.control_plane.to_dict()
        # override the default output from pydantic by calling `to_dict()` of data_plane
        if self.data_plane:
            _dict['dataPlane'] = self.data_plane.to_dict()
        # override the default output from pydantic by calling `to_dict()` of system_plane
        if self.system_plane:
            _dict['systemPlane'] = self.system_plane.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1TroubleshootingTopSitesByAlertsPostResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "controlPlane": V1TroubleshootingTopSitesByAlertsPostResponseSiteCounts.from_dict(obj["controlPlane"]) if obj.get("controlPlane") is not None else None,
            "dataPlane": V1TroubleshootingTopSitesByAlertsPostResponseSiteCounts.from_dict(obj["dataPlane"]) if obj.get("dataPlane") is not None else None,
            "systemPlane": V1TroubleshootingTopSitesByAlertsPostResponseSiteCounts.from_dict(obj["systemPlane"]) if obj.get("systemPlane") is not None else None
        })
        return _obj


